(()=>{'use strict';
const PATHS={script:'mousetrap_script_data.json',translations:'mousetrap_line_translations.json',vocabulary:'mousetrap_line_vocabulary.json',grammar:'mousetrap_line_grammar.json',dictionary:'mousetrap_word_dictionary.json',structure:'mousetrap_line_structure.json'};
const EXPECTED=[['act1-scene1',190],['act1-scene2',336],['act2',638]];
const state={script:null,translations:{},vocabulary:{},grammar:{},dictionary:{},structure:null,coreStatus:'idle',studyStatus:'idle',structureStatus:'idle',errors:{}};
const events=new EventTarget();let corePromise=null,studyPromise=null,structurePromise=null;
function emit(type,detail={}){events.dispatchEvent(new CustomEvent(type,{detail:{...detail,state:snapshot()}}))}
function snapshot(){return{coreStatus:state.coreStatus,studyStatus:state.studyStatus,structureStatus:state.structureStatus,errors:{...state.errors},hasScript:!!state.script,hasTranslations:!!Object.keys(state.translations).length,hasVocabulary:!!Object.keys(state.vocabulary).length,hasGrammar:!!Object.keys(state.grammar).length,hasDictionary:!!Object.keys(state.dictionary).length,hasStructure:!!state.structure}}
function validateScript(data){if(!data||typeof data!=='object'||Array.isArray(data))throw Error('SCRIPT_DATA_INVALID');let total=0;for(const[id,count]of EXPECTED){const rows=data[id]?.speeches;if(!Array.isArray(rows)||rows.length!==count)throw Error(`SCRIPT_SCENE_INVALID:${id}`);for(let i=0;i<rows.length;i++){const row=rows[i];if(!row||typeof row.id!=='string'||!String(row.speaker||'').trim()||!String(row.text||'').trim())throw Error(`SCRIPT_ROW_INVALID:${id}:${i+1}`)}total+=rows.length}if(total!==1164)throw Error('SCRIPT_TOTAL_INVALID');return data}
function validateStructure(data){if(!data||data.schemaVersion!==1||data.counts?.speeches!==1164||data.counts?.sentences!==2277||data.counts?.chunks!==8055)throw Error('STRUCTURE_DATA_INVALID');return data}
async function fetchJson(path,{timeoutMs=10000}={}){const controller=new AbortController();const timer=setTimeout(()=>controller.abort(new DOMException('Timed out','TimeoutError')),timeoutMs);try{const response=await fetch(`./${path}`,{signal:controller.signal,credentials:'same-origin',cache:'default'});if(!response.ok)throw Error(`${path}:HTTP_${response.status}`);return await response.json()}catch(error){if(error?.name==='AbortError'||error?.name==='TimeoutError')throw Error(`${path}:TIMEOUT_${timeoutMs}`);throw error}finally{clearTimeout(timer)}}
async function loadCore({force=false}={}){if(state.script&&!force)return state.script;if(corePromise&&!force)return corePromise;state.coreStatus='loading';delete state.errors.script;emit('core-loading');corePromise=(async()=>{try{const data=validateScript(await fetchJson(PATHS.script,{timeoutMs:10000}));state.script=data;state.coreStatus='ready';emit('core-ready');return data}catch(error){state.coreStatus='error';state.errors.script=String(error?.message||error);emit('core-error',{error:state.errors.script});throw error}finally{corePromise=null}})();return corePromise}
async function loadStudy({force=false}={}){if(state.studyStatus==='ready'&&!force)return studySnapshot();if(studyPromise&&!force)return studyPromise;state.studyStatus='loading';emit('study-loading');const specs=[['translations',PATHS.translations],['vocabulary',PATHS.vocabulary],['grammar',PATHS.grammar],['dictionary',PATHS.dictionary]];studyPromise=(async()=>{const results=await Promise.allSettled(specs.map(([,path])=>fetchJson(path,{timeoutMs:10000})));let failures=0;results.forEach((result,i)=>{const[key]=specs[i];if(result.status==='fulfilled'){state[key]=result.value||{};delete state.errors[key]}else{failures++;state.errors[key]=String(result.reason?.message||result.reason);state[key]=state[key]||{}}});state.studyStatus=failures?'partial':'ready';emit(failures?'study-partial':'study-ready',{failures});return studySnapshot()})().finally(()=>{studyPromise=null});return studyPromise}
function studySnapshot(){return{translations:state.translations,vocabulary:state.vocabulary,grammar:state.grammar,dictionary:state.dictionary,status:state.studyStatus,errors:{...state.errors}}}
async function loadStructure({force=false}={}){if(state.structure&&!force)return state.structure;if(structurePromise&&!force)return structurePromise;state.structureStatus='loading';delete state.errors.structure;emit('structure-loading');structurePromise=(async()=>{try{state.structure=validateStructure(await fetchJson(PATHS.structure,{timeoutMs:12000}));state.structureStatus='ready';emit('structure-ready');return state.structure}catch(error){state.structureStatus='error';state.errors.structure=String(error?.message||error);emit('structure-error',{error:state.errors.structure});throw error}finally{structurePromise=null}})();return structurePromise}
function annotation(id){return{translation:state.translations[id]?.translation||'',translationSource:state.translations[id]?.translationSource||'',vocabulary:Array.isArray(state.vocabulary[id])?state.vocabulary[id]:[],grammar:Array.isArray(state.grammar[id])?state.grammar[id]:[]}}
function on(type,listener,options){events.addEventListener(type,listener,options);return()=>events.removeEventListener(type,listener,options)}
const api={version:19,loadCore,loadStudy,loadStructure,fetchJson,on,snapshot,annotation,get script(){return state.script},get translations(){return state.translations},get vocabulary(){return state.vocabulary},get grammar(){return state.grammar},get dictionary(){return state.dictionary},get structure(){return state.structure}};
window.MTS_DATA=Object.freeze(api);
})();
