(()=>{'use strict';
const EXPECTED=[['act1-scene1','act1-scene1-speech-',190,'Act I · Scene I'],['act1-scene2','act1-scene2-speech-',336,'Act I · Scene II'],['act2','act2-speech-',638,'Act II']];
const PATHS={script:'mousetrap_script_data.json',translations:'mousetrap_line_translations.json',vocabulary:'mousetrap_line_vocabulary.json',grammar:'mousetrap_line_grammar.json',dictionary:'mousetrap_word_dictionary.json'};
const EXPECTED_IDS=EXPECTED.flatMap(([s,p,n])=>Array.from({length:n},(_,i)=>p+String(i+1).padStart(4,'0')));const IDSET=new Set(EXPECTED_IDS);
const CAST=['MOLLIE','TROTTER','GILES','MISS CASEWELL','CHRISTOPHER','MRS. BOYLE','PARAVICINI','MAJOR METCALF'];
const KEY={selectedScene:'mts.selectedSceneId',character:'mts.characterId',lineCurrent:'mts.lineDetail.current',practicePending:'mts.practice.pending',sceneProgress:'mts.sceneProgress',cueRatings:'mts.practice.cue.ratings',cueState:'mts.practice.cue.state',rehearsalState:'mts.practice.rehearsal.state',readerMode:'mts.reader.mode',readerProgress:'mts.reader.progress',readerLast:'mts.reader.lastPosition'};
const $=id=>document.getElementById(id),app=$('app'),gate=$('dataGate'),status=$('gateStatus');let D=null,SEARCH=[],toastTimer=0;
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]||c))}
function parse(raw,f){try{return raw?JSON.parse(raw):f}catch{return f}}
function obj(v,n){if(!v||typeof v!=='object'||Array.isArray(v))throw Error(`${n}: object required`)}
function exactKeys(v,n){obj(v,n);const k=Object.keys(v);if(k.length!==1164)throw Error(`${n}: expected 1164 keys, got ${k.length}`);const miss=EXPECTED_IDS.filter(x=>!(x in v)),extra=k.filter(x=>!IDSET.has(x));if(miss.length||extra.length)throw Error(`${n}: ID mismatch missing=${miss.length} extra=${extra.length}`)}
function validateScript(d){obj(d,'script');let total=0;for(const [sid,prefix,n] of EXPECTED){const s=d[sid];if(!s||!Array.isArray(s.speeches))throw Error(`script.${sid}.speeches missing`);if(s.speeches.length!==n)throw Error(`script.${sid}: ${s.speeches.length}/${n}`);s.speeches.forEach((x,i)=>{const id=prefix+String(i+1).padStart(4,'0');if(!x||x.id!==id)throw Error(`script order/id mismatch ${sid} #${i+1}`);if(!String(x.speaker||'').trim()||!String(x.text||'').trim())throw Error(`script empty speaker/text ${id}`)});total+=n}if(total!==1164)throw Error('script total mismatch')}
function validateTranslations(d){exactKeys(d,'translations');for(const id of EXPECTED_IDS){const x=d[id];obj(x,`translations.${id}`);if(!String(x.translation||'').trim()||!String(x.translationSource||'').trim())throw Error(`translations invalid ${id}`)}return 1164}
function validateVocabulary(d){exactKeys(d,'vocabulary');let n=0;for(const id of EXPECTED_IDS){if(!Array.isArray(d[id]))throw Error(`vocabulary.${id}: array required`);for(const x of d[id]){obj(x,'vocab entry');for(const k of ['surface','lemma','meaning'])if(!String(x[k]||'').trim())throw Error(`vocabulary.${id}.${k} invalid`);n++}}if(n!==1186)throw Error(`vocabulary items ${n}/1186`);return n}
function validateGrammar(d){exactKeys(d,'grammar');let n=0;for(const id of EXPECTED_IDS){if(!Array.isArray(d[id]))throw Error(`grammar.${id}: array required`);for(const x of d[id]){obj(x,'grammar entry');if(!String(x.pattern||'').trim()||!String(x.description||'').trim())throw Error(`grammar.${id} invalid`);n++}}if(n!==692)throw Error(`grammar items ${n}/692`);return n}
function validateDictionary(d,vocab){obj(d,'dictionary');const keys=Object.keys(d);if(keys.length!==578)throw Error(`dictionary entries ${keys.length}/578`);const norm=s=>String(s||'').toLowerCase().trim();const set=new Set(keys.map(norm));let missing=0;for(const id of EXPECTED_IDS)for(const x of vocab[id])if(!set.has(norm(x.lemma)))missing++;if(missing)throw Error(`dictionary missing refs ${missing}`);return keys.length}
async function json(path){if(window.MTS_PRIVATE_DATA?.getVerifiedResponse){const vr=await window.MTS_PRIVATE_DATA.getVerifiedResponse(path);if(!vr)throw Error(`${path}: verified production response unavailable`);return vr.json()}const r=await fetch(path,{cache:'no-store'});if(!r.ok)throw Error(`${path}: HTTP ${r.status}`);return r.json()}
function normalize(s){return String(s||'').normalize('NFKC').toLowerCase().replace(/\s+/g,' ').trim()}
function sceneLabel(id){return EXPECTED.find(x=>x[0]===id)?.[3]||id}
function validScene(x){return EXPECTED.some(a=>a[0]===x)}
function validLine(scene,id){return !!D&&validScene(scene)&&D.script[scene].speeches.some(x=>x.id===id)}
function speechById(scene,id){return D?.script?.[scene]?.speeches?.find(x=>x.id===id)||null}
function selectedScene(){const x=localStorage.getItem(KEY.selectedScene);return validScene(x)?x:'act1-scene1'}
function currentRole(){const c=localStorage.getItem(KEY.character)||'';return CAST.includes(c)?c:''}
function readerMode(){const m=localStorage.getItem(KEY.readerMode)||'full';return ['full','mine','cue'].includes(m)?m:'full'}
function setReaderMode(m){if(!['full','mine','cue'].includes(m))m='full';localStorage.setItem(KEY.readerMode,m)}
function buildSearch(){const out=[];for(const [sceneId] of EXPECTED){for(const x of D.script[sceneId].speeches){const t=D.translations[x.id]?.translation||'',v=D.vocabulary[x.id]||[];const vocabText=v.flatMap(z=>[z.surface,z.lemma,z.meaning]).join(' ');out.push({sceneId,id:x.id,speaker:x.speaker,text:x.text,translation:t,vocab:v,haystack:normalize([x.speaker,x.text,t,vocabText].join('\n'))})}}SEARCH=out}
function sanitize(){const s=localStorage.getItem(KEY.selectedScene);if(!validScene(s))localStorage.setItem(KEY.selectedScene,'act1-scene1');const c=localStorage.getItem(KEY.character);if(c&&!CAST.includes(c))localStorage.removeItem(KEY.character);setReaderMode(readerMode());try{const x=JSON.parse(localStorage.getItem(KEY.lineCurrent)||'null');if(x&&(!validScene(x.sceneId)||!validLine(x.sceneId,x.lineId)))localStorage.removeItem(KEY.lineCurrent)}catch{localStorage.removeItem(KEY.lineCurrent)}try{const p=JSON.parse(localStorage.getItem(KEY.practicePending)||'null');if(p&&(!validScene(p.sceneId)||(p.lineId&&!validLine(p.sceneId,p.lineId))))localStorage.removeItem(KEY.practicePending)}catch{localStorage.removeItem(KEY.practicePending)}const rp=parse(localStorage.getItem(KEY.readerProgress),null);if(rp&&typeof rp==='object'){rp.globalSeen=Array.isArray(rp.globalSeen)?rp.globalSeen.filter(id=>IDSET.has(id)):[];rp.roles=rp.roles&&typeof rp.roles==='object'?rp.roles:{};for(const k of Object.keys(rp.roles)){if(!CAST.includes(k)||!Array.isArray(rp.roles[k]))delete rp.roles[k];else rp.roles[k]=rp.roles[k].filter(id=>IDSET.has(id))}if(rp.last&&(!validScene(rp.last.sceneId)||!validLine(rp.last.sceneId,rp.last.lineId)))delete rp.last;localStorage.setItem(KEY.readerProgress,JSON.stringify(rp))}}
function readerProgress(){const p=parse(localStorage.getItem(KEY.readerProgress),{})||{};return{version:1,globalSeen:Array.isArray(p.globalSeen)?p.globalSeen:[],roles:p.roles&&typeof p.roles==='object'?p.roles:{},last:p.last&&typeof p.last==='object'?p.last:null,updatedAt:p.updatedAt||''}}
function markReaderSeen(scene,id){if(!validLine(scene,id))return;const p=readerProgress(),role=currentRole(),x=speechById(scene,id);if(!p.globalSeen.includes(id))p.globalSeen.push(id);if(role&&x?.speaker===role){if(!Array.isArray(p.roles[role]))p.roles[role]=[];if(!p.roles[role].includes(id))p.roles[role].push(id)}p.last={sceneId:scene,lineId:id,role:role||'',updatedAt:new Date().toISOString()};p.updatedAt=p.last.updatedAt;localStorage.setItem(KEY.readerProgress,JSON.stringify(p));localStorage.setItem(KEY.readerLast,JSON.stringify(p.last))}
function shell(body,active='home'){const role=currentRole();app.innerHTML=`<main class="shell"><div class="top"><div><div class="eyebrow">Script to Stage · Production</div><div class="brand">The Mousetrap Trainer</div></div><button class="ghost-btn" data-action="role">${role?`Role · ${esc(role)}`:'Role'}</button></div>${body}</main><nav class="bottom-nav">${[['home','Home'],['script','Script'],['practice','Practice'],['progress','Progress'],['more','More']].map(([r,l])=>`<button data-nav="${r}" class="${active===r?'active':''}">${l}</button>`).join('')}</nav>`;app.querySelectorAll('[data-nav]').forEach(b=>b.onclick=()=>go(`#/${b.dataset.nav}`));const rb=app.querySelector('[data-action=role]');if(rb)rb.onclick=()=>go('#/more')}
function go(h){if(location.hash===h)route();else location.hash=h}
function toast(t){clearTimeout(toastTimer);$('toast').textContent=t;$('toast').classList.add('show');toastTimer=setTimeout(()=>$('toast').classList.remove('show'),1500)}
function continueReader(){const p=readerProgress(),last=p.last||parse(localStorage.getItem(KEY.readerLast),null);if(last&&validLine(last.sceneId,last.lineId)){localStorage.setItem(KEY.selectedScene,last.sceneId);go(`#/script?line=${encodeURIComponent(last.lineId)}`);return true}return false}
function home(){const s=selectedScene(),role=currentRole(),p=readerProgress(),last=p.last&&validLine(p.last.sceneId,p.last.lineId)?p.last:null;shell(`<section class="card hero"><div class="eyebrow">Continue</div><h1>台本を覚える</h1><p class="muted">Reader・Cue Practice・Rehearsal・Progressを同じScene/Role状態で接続します。</p><div class="toolbar"><button class="primary-btn" data-open="script">${esc(sceneLabel(s))} を開く</button>${last?'<button class="ghost-btn" data-open="last">前回の台詞へ</button>':''}<button class="ghost-btn" data-open="practice">Practice</button><button class="ghost-btn" data-open="search">Search</button></div><p class="muted">Role: ${esc(role||'未選択')}</p></section><section class="grid" style="margin-top:12px">${EXPECTED.map(([id,,,label])=>`<button class="scene-card" data-scene="${id}"><b>${esc(label)}</b><div class="muted">${D.script[id].speeches.length} speeches</div></button>`).join('')}</section>`,'home');app.querySelector('[data-open=script]').onclick=()=>go('#/script');const lastBtn=app.querySelector('[data-open=last]');if(lastBtn)lastBtn.onclick=continueReader;app.querySelector('[data-open=practice]').onclick=()=>go('#/practice');app.querySelector('[data-open=search]').onclick=()=>go('#/search');app.querySelectorAll('[data-scene]').forEach(b=>b.onclick=()=>{localStorage.setItem(KEY.selectedScene,b.dataset.scene);go('#/script')})}
function readerRows(scene,mode,role){const speeches=D.script[scene].speeches;if(mode==='full')return speeches.map(x=>({x,kind:'full'}));if(!role)return[];if(mode==='mine')return speeches.filter(x=>x.speaker===role).map(x=>({x,kind:'target'}));const wanted=new Map();for(let i=0;i<speeches.length;i++){if(speeches[i].speaker!==role)continue;if(i>0)wanted.set(speeches[i-1].id,{x:speeches[i-1],kind:'cue'});wanted.set(speeches[i].id,{x:speeches[i],kind:'target'})}return speeches.filter(x=>wanted.has(x.id)).map(x=>wanted.get(x.id))}
function script(){const scene=selectedScene(),q=new URLSearchParams(location.hash.split('?')[1]||''),focus=q.get('line'),role=currentRole(),mode=readerMode();if((mode==='mine'||mode==='cue')&&!role){setReaderMode('full');toast('Mine / Cue FocusにはRoleを選択してください')}const activeMode=readerMode(),rows=readerRows(scene,activeMode,role);shell(`<section class="card"><div class="eyebrow">Script</div><h2>${esc(sceneLabel(scene))}</h2><div class="toolbar"><button class="ghost-btn" data-scene-picker>Scene</button><button class="ghost-btn ${activeMode==='full'?'selected-tool':''}" data-reader-mode="full">Full</button><button class="ghost-btn ${activeMode==='mine'?'selected-tool':''}" data-reader-mode="mine">Mine</button><button class="ghost-btn ${activeMode==='cue'?'selected-tool':''}" data-reader-mode="cue">Cue Focus</button><button class="ghost-btn" data-open-search>Search</button></div><p class="muted">Role: ${esc(role||'未選択')} · ${rows.length}/${D.script[scene].speeches.length} lines shown</p></section><section style="margin-top:12px" data-lines>${rows.length?rows.map(({x,kind})=>`<button class="line-row ${kind==='cue'?'cue-row':''} ${kind==='target'?'target-row':''}" id="${x.id}" data-line="${x.id}"><span class="speaker">${esc(x.speaker)}${kind==='cue'?'<small class="row-tag">CUE</small>':kind==='target'&&activeMode==='cue'?'<small class="row-tag target">YOUR LINE</small>':''}</span><span class="line-text">${esc(x.text)}</span></button>`).join(''):`<div class="card"><p class="muted">このRoleにはこのSceneの台詞がありません。</p></div>`}</section>`,'script');app.querySelector('[data-scene-picker]').onclick=()=>go('#/scene');app.querySelector('[data-open-search]').onclick=()=>go('#/search');app.querySelectorAll('[data-reader-mode]').forEach(b=>b.onclick=()=>{const m=b.dataset.readerMode;if((m==='mine'||m==='cue')&&!currentRole()){toast('先にRoleを選択してください');go('#/more');return}setReaderMode(m);script()});app.querySelectorAll('[data-line]').forEach(b=>b.onclick=()=>openLine(scene,b.dataset.line));if(focus&&validLine(scene,focus))setTimeout(()=>document.getElementById(focus)?.scrollIntoView({block:'center'}),0)}
function scene(){const p=parse(localStorage.getItem(KEY.sceneProgress),{})||{};shell(`<section class="card"><div class="eyebrow">Scene Navigator</div><h2>Sceneを選択</h2></section><section class="grid" style="margin-top:12px">${EXPECTED.map(([id,,,label])=>`<button class="scene-card" data-open-scene="${id}"><b>${esc(label)}</b><div class="muted">${D.script[id].speeches.length} speeches</div><span class="chip">${Math.round(Number(p[id]||0))}% · Open Script</span></button>`).join('')}</section>`,'script');app.querySelectorAll('[data-open-scene]').forEach(b=>b.onclick=()=>{localStorage.setItem(KEY.selectedScene,b.dataset.openScene);go('#/script')})}
function openLine(scene,line){if(!validLine(scene,line))return;markReaderSeen(scene,line);localStorage.setItem(KEY.lineCurrent,JSON.stringify({sceneId:scene,lineId:line}));$('learningOverlay').hidden=false;location.hash=`#/line?scene=${encodeURIComponent(scene)}&line=${encodeURIComponent(line)}`}
function closeOverlays(){['learningOverlay','cueOverlay','rehearsalOverlay'].forEach(id=>$(id).hidden=true)}
function lineRoute(q){const s=q.get('scene'),l=q.get('line');if(!validLine(s,l)){history.replaceState(null,'','#/script');return route()}localStorage.setItem(KEY.selectedScene,s);markReaderSeen(s,l);localStorage.setItem(KEY.lineCurrent,JSON.stringify({sceneId:s,lineId:l}));$('learningOverlay').hidden=false;$('learningFrame').contentWindow?.postMessage({type:'mts:line',sceneId:s,lineId:l},'*')}
function practice(){const s=selectedScene(),role=currentRole();shell(`<section class="card"><div class="eyebrow">Practice</div><h2>${esc(sceneLabel(s))}</h2><p class="muted">Role: ${esc(role||'未選択')}</p>${!role?'<p class="error">Cue / Rehearsalを始める前にRoleを選択してください。</p>':''}</section><section class="grid" style="margin-top:12px"><button class="mode-btn" data-p="cue"><b>Cue Practice</b><div class="muted">直前Cueから自分の台詞を思い出す</div></button><button class="mode-btn" data-p="rehearsal"><b>Rehearsal</b><div class="muted">通し稽古・TTS・音声認識</div></button></section>`,'practice');app.querySelector('[data-p=cue]').onclick=()=>role?startPractice('cue',s):go('#/more');app.querySelector('[data-p=rehearsal]').onclick=()=>role?startPractice('rehearsal',s):go('#/more')}
function startPractice(mode,scene,lineId=''){localStorage.setItem(KEY.practicePending,JSON.stringify({mode,sceneId:scene,lineId}));if(mode==='cue')go(`#/cue?scene=${encodeURIComponent(scene)}${lineId?`&line=${encodeURIComponent(lineId)}`:''}`);else go(`#/rehearsal?scene=${encodeURIComponent(scene)}${lineId?`&line=${encodeURIComponent(lineId)}`:''}`)}
function cueRoute(q){const s=validScene(q.get('scene'))?q.get('scene'):selectedScene(),l=q.get('line')||'';if(l&&!validLine(s,l)){history.replaceState(null,'','#/practice');return route()}localStorage.setItem(KEY.selectedScene,s);localStorage.setItem(KEY.practicePending,JSON.stringify({mode:'cue',sceneId:s,lineId:l}));$('cueOverlay').hidden=false;$('cueFrame').contentWindow?.postMessage({type:'mts:start-cue',sceneId:s,lineId:l},'*')}
function rehearsalRoute(q){const s=validScene(q.get('scene'))?q.get('scene'):selectedScene(),l=q.get('line')||'';if(l&&!validLine(s,l)){history.replaceState(null,'','#/practice');return route()}localStorage.setItem(KEY.selectedScene,s);localStorage.setItem(KEY.practicePending,JSON.stringify({mode:'rehearsal',sceneId:s,lineId:l}));$('rehearsalOverlay').hidden=false;$('rehearsalFrame').contentWindow?.postMessage({type:'mts:start-rehearsal',sceneId:s,lineId:l},'*')}
function roleLineCount(role){if(!role)return 0;let n=0;for(const [id] of EXPECTED)n+=D.script[id].speeches.filter(x=>x.speaker===role).length;return n}
function progress(){let p={};try{p=JSON.parse(localStorage.getItem(KEY.sceneProgress)||'{}')}catch{}const a=Number(p['act1-scene1']||0),b=Number(p['act1-scene2']||0),c=Number(p.act2||0),act1=Math.round((a*190+b*336)/526),overall=Math.round((a*190+b*336+c*638)/1164);const role=currentRole(),rp=readerProgress(),roleSeen=role&&Array.isArray(rp.roles[role])?rp.roles[role].length:0,roleTotal=roleLineCount(role),cue=parse(localStorage.getItem(KEY.cueRatings),{})||{},cueRows=Object.values(cue).filter(x=>x&&(!role||x.character===role)),good=cueRows.filter(x=>x.last==='good'||x.rating==='good').length,hard=cueRows.filter(x=>x.last==='hard'||x.rating==='hard').length,again=cueRows.filter(x=>x.last==='again'||x.rating==='again').length,reh=parse(localStorage.getItem(KEY.rehearsalState),{})||{},rehCount=Object.keys(reh).filter(k=>!role||k.endsWith(`|${role}`)).length;shell(`<section class="card"><div class="eyebrow">Progress</div><h2>学習進捗</h2><p class="muted">Role: ${esc(role||'未選択')}</p><div class="progress-summary"><div><div class="stat">${rp.globalSeen.length}</div><div class="muted">Reader opened / 1164</div></div><div><div class="stat">${cueRows.length}</div><div class="muted">Cue rated</div></div><div><div class="stat">${rehCount}</div><div class="muted">Rehearsal states</div></div></div>${role?`<p><b>${esc(role)} Reader</b> ${roleSeen}/${roleTotal}</p><div class="progress-bar"><i style="width:${roleTotal?Math.round(roleSeen/roleTotal*100):0}%"></i></div>`:''}<div class="toolbar"><span class="chip">Got it ${good}</span><span class="chip">Hard ${hard}</span><span class="chip">Again ${again}</span></div></section><section class="card" style="margin-top:12px"><div class="grid"><div><div class="stat" data-act1>${act1}%</div><div class="muted">Act I</div></div><div><div class="stat" data-act2>${Math.round(c)}%</div><div class="muted">Act II</div></div><div><div class="stat" data-overall>${overall}%</div><div class="muted">Overall practice</div></div></div>${EXPECTED.map(([id,,,label])=>`<p><b>${esc(label)}</b> ${Math.round(Number(p[id]||0))}%</p><div class="progress-bar"><i style="width:${Math.max(0,Math.min(100,Number(p[id]||0)))}%"></i></div>`).join('')}</section>`,'progress')}
function more(){const role=currentRole();shell(`<section class="card"><div class="eyebrow">More</div><h2>役を選択</h2><p class="muted">選択したRoleはReader / Cue Practice / Rehearsal / Progressで共通利用されます。役変更で既存progressは削除しません。</p><div class="grid">${CAST.map(c=>`<button class="role-btn" data-role="${esc(c)}"><b>${esc(c)}</b>${c===role?'<div class="chip">Selected</div>':''}</button>`).join('')}</div></section><section class="card" style="margin-top:12px"><h3>Tools</h3><div class="toolbar"><button class="ghost-btn" data-more-search>Search</button><button class="ghost-btn" data-more-scene>Scene Navigator</button></div></section>`,'more');app.querySelectorAll('[data-role]').forEach(b=>b.onclick=()=>{localStorage.setItem(KEY.character,b.dataset.role);toast(`${b.dataset.role} selected`);more()});app.querySelector('[data-more-search]').onclick=()=>go('#/search');app.querySelector('[data-more-scene]').onclick=()=>go('#/scene')}
function matchKinds(e,q){const n=normalize(q),k=[];if(normalize(e.text).includes(n))k.push('Line');if(normalize(e.speaker).includes(n))k.push('Speaker');if(normalize(e.translation).includes(n))k.push('日本語訳');if(e.vocab.some(v=>normalize([v.surface,v.lemma,v.meaning].join(' ')).includes(n)))k.push('Vocabulary');return k}
function searchRoute(q){const initial=q.get('q')||'';shell(`<section class="card"><div class="eyebrow">Search</div><h2>台本検索</h2><form class="search-form" id="searchForm"><input id="searchInput" type="search" autocomplete="off" enterkeyhint="search" placeholder="台詞・speaker・英単語・日本語訳" value="${esc(initial)}"><button class="primary-btn" type="submit">Search</button></form><p class="muted">結果をタップすると該当speechのLine Detailへ移動します。</p></section><section id="searchResults" style="margin-top:12px"></section>`,'script');const input=$('searchInput'),results=$('searchResults');function run(raw){const term=raw.trim();if(!term){results.innerHTML='<div class="card"><p class="muted">検索語を入力してください。</p></div>';return}const n=normalize(term),hits=SEARCH.filter(e=>e.haystack.includes(n)).slice(0,120);results.innerHTML=hits.length?hits.map(e=>{const kinds=matchKinds(e,term);return `<button class="search-result" data-search-line="${e.id}" data-search-scene="${e.sceneId}"><span><b>${esc(e.speaker)}</b> · ${esc(sceneLabel(e.sceneId))}</span><span class="search-line">${esc(e.text)}</span>${e.translation?`<span class="search-translation">${esc(e.translation)}</span>`:''}<span class="search-kinds">${kinds.map(k=>`<i>${esc(k)}</i>`).join('')}</span></button>`}).join(''):`<div class="card"><p>「${esc(term)}」の結果はありません。</p></div>`;results.querySelectorAll('[data-search-line]').forEach(b=>b.onclick=()=>{localStorage.setItem(KEY.selectedScene,b.dataset.searchScene);openLine(b.dataset.searchScene,b.dataset.searchLine)})}$('searchForm').onsubmit=ev=>{ev.preventDefault();const term=input.value.trim();history.replaceState(null,'',`#/search${term?`?q=${encodeURIComponent(term)}`:''}`);run(term)};run(initial)}
function route(){if(!D)return;closeOverlays();sanitize();const [path,qs='']=location.hash.replace(/^#/,'').split('?'),q=new URLSearchParams(qs);switch(path||'/home'){case'/home':home();break;case'/script':script();break;case'/scene':scene();break;case'/practice':practice();break;case'/progress':progress();break;case'/more':more();break;case'/search':searchRoute(q);break;case'/line':lineRoute(q);break;case'/cue':cueRoute(q);break;case'/rehearsal':rehearsalRoute(q);break;default:history.replaceState(null,'','#/home');home()}}
async function load(){gate.hidden=false;status.classList.remove('error');status.textContent='Loading production datasets…';const [script,translations,vocabulary,grammar,dictionary]=await Promise.all(Object.values(PATHS).map(json));validateScript(script);const tc=validateTranslations(translations),vc=validateVocabulary(vocabulary),gc=validateGrammar(grammar),dc=validateDictionary(dictionary,vocabulary);D={script,translations,vocabulary,grammar,dictionary};buildSearch();window.MTS_SHARED_SCRIPT_DATA=script;window.MTS_SHARED_LINE_ANNOTATIONS=Object.fromEntries(EXPECTED_IDS.map(id=>[id,{translation:translations[id].translation,translationSource:translations[id].translationSource,vocabulary:vocabulary[id],grammar:grammar[id]}]));window.MTS_SHARED_WORD_DICTIONARY=dictionary;window.MTS_P5_QA={status:'PASS',speeches:1164,scenes:[190,336,638],translations:tc,vocabulary:vc,grammar:gc,dictionary:dc};sanitize();gate.hidden=true;route();return window.MTS_P5_QA}
function showDataFailure(e){gate.hidden=false;status.textContent=`PRODUCTION DATA UNAVAILABLE\n${e?.message||e}\n配布bundleのcanonical JSONを確認してください。保存済みのRole・Reader位置・Practice progressは保持されています。`;status.classList.add('error')}
window.addEventListener('hashchange',route);window.addEventListener('message',e=>{const m=e.data||{};if(m.type==='mts:navigate'){if(m.target==='practice')go('#/practice');if(m.target==='script')go('#/script');if(m.target==='progress')go('#/progress');if(m.target==='line'&&validLine(m.sceneId,m.lineId)){localStorage.setItem(KEY.selectedScene,m.sceneId);openLine(m.sceneId,m.lineId)}}if(m.type==='mts:scene-progress-changed'&&location.hash.startsWith('#/progress'))progress()});$('retryBtn').onclick=()=>load().catch(showDataFailure);load().catch(showDataFailure);
})();
