(()=>{'use strict';
const EXPECTED=[['act1-scene1','act1-scene1-speech-',190,'Act I · Scene I'],['act1-scene2','act1-scene2-speech-',336,'Act I · Scene II'],['act2','act2-speech-',638,'Act II']];
const PATHS={script:'mousetrap_script_data.json',translations:'mousetrap_line_translations.json',vocabulary:'mousetrap_line_vocabulary.json',grammar:'mousetrap_line_grammar.json',dictionary:'mousetrap_word_dictionary.json'};
const EXPECTED_IDS=EXPECTED.flatMap(([s,p,n])=>Array.from({length:n},(_,i)=>p+String(i+1).padStart(4,'0')));const IDSET=new Set(EXPECTED_IDS);const CAST=['MOLLIE','TROTTER','GILES','MISS CASEWELL','CHRISTOPHER','MRS. BOYLE','PARAVICINI','MAJOR METCALF'];
const $=id=>document.getElementById(id), app=$('app'), gate=$('dataGate'), status=$('gateStatus');let D=null;let toastTimer=0;
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}function obj(v,n){if(!v||typeof v!=='object'||Array.isArray(v))throw Error(`${n}: object required`)}
function exactKeys(v,n){obj(v,n);const k=Object.keys(v);if(k.length!==1164)throw Error(`${n}: expected 1164 keys, got ${k.length}`);const miss=EXPECTED_IDS.filter(x=>!(x in v)),extra=k.filter(x=>!IDSET.has(x));if(miss.length||extra.length)throw Error(`${n}: ID mismatch missing=${miss.length} extra=${extra.length}`)}
function validateScript(d){obj(d,'script');let total=0;for(const [sid,prefix,n] of EXPECTED){const s=d[sid];if(!s||!Array.isArray(s.speeches))throw Error(`script.${sid}.speeches missing`);if(s.speeches.length!==n)throw Error(`script.${sid}: ${s.speeches.length}/${n}`);s.speeches.forEach((x,i)=>{const id=prefix+String(i+1).padStart(4,'0');if(!x||x.id!==id)throw Error(`script order/id mismatch ${sid} #${i+1}`);if(!String(x.speaker||'').trim()||!String(x.text||'').trim())throw Error(`script empty speaker/text ${id}`)});total+=n}if(total!==1164)throw Error('script total mismatch')}
function validateTranslations(d){exactKeys(d,'translations');for(const id of EXPECTED_IDS){const x=d[id];obj(x,`translations.${id}`);if(!String(x.translation||'').trim()||!String(x.translationSource||'').trim())throw Error(`translations invalid ${id}`)}}
function validateVocabulary(d){exactKeys(d,'vocabulary');let n=0;for(const id of EXPECTED_IDS){if(!Array.isArray(d[id]))throw Error(`vocabulary.${id}: array required`);for(const x of d[id]){obj(x,'vocab entry');for(const k of ['surface','lemma','meaning'])if(!String(x[k]||'').trim())throw Error(`vocabulary.${id}.${k} invalid`);n++}}if(n!==1186)throw Error(`vocabulary items ${n}/1186`);return n}
function validateGrammar(d){exactKeys(d,'grammar');let n=0;for(const id of EXPECTED_IDS){if(!Array.isArray(d[id]))throw Error(`grammar.${id}: array required`);for(const x of d[id]){obj(x,'grammar entry');if(!String(x.pattern||'').trim()||!String(x.description||'').trim())throw Error(`grammar.${id} invalid`);n++}}if(n!==692)throw Error(`grammar items ${n}/692`);return n}
function validateDictionary(d,vocab){obj(d,'dictionary');const keys=Object.keys(d);if(keys.length!==578)throw Error(`dictionary entries ${keys.length}/578`);const norm=s=>String(s||'').toLowerCase().trim();const set=new Set(keys.map(norm));let missing=0;for(const id of EXPECTED_IDS)for(const x of vocab[id])if(!set.has(norm(x.lemma)))missing++;if(missing)throw Error(`dictionary missing refs ${missing}`);return keys.length}
async function json(path){const r=await fetch(path,{cache:'no-store'});if(!r.ok)throw Error(`${path}: HTTP ${r.status}`);return r.json()}
async function load(){gate.hidden=false;status.textContent='Loading production datasets…';const [script,translations,vocabulary,grammar,dictionary]=await Promise.all(Object.values(PATHS).map(json));validateScript(script);validateTranslations(translations);const vc=validateVocabulary(vocabulary),gc=validateGrammar(grammar),dc=validateDictionary(dictionary,vocabulary);D={script,translations,vocabulary,grammar,dictionary};window.MTS_SHARED_SCRIPT_DATA=script;window.MTS_SHARED_LINE_ANNOTATIONS=Object.fromEntries(EXPECTED_IDS.map(id=>[id,{translation:translations[id].translation,translationSource:translations[id].translationSource,vocabulary:vocabulary[id],grammar:grammar[id]}]));window.MTS_SHARED_WORD_DICTIONARY=dictionary;window.MTS_P5_QA={status:'PASS',speeches:1164,scenes:[190,336,638],vocabulary:vc,grammar:gc,dictionary:dc};sanitize();gate.hidden=true;route();return window.MTS_P5_QA}
function toast(t){clearTimeout(toastTimer);$('toast').textContent=t;$('toast').classList.add('show');toastTimer=setTimeout(()=>$('toast').classList.remove('show'),1300)}
function validScene(x){return EXPECTED.some(a=>a[0]===x)}function validLine(scene,id){return validScene(scene)&&D.script[scene].speeches.some(x=>x.id===id)}function sanitize(){const s=localStorage.getItem('mts.selectedSceneId');if(!validScene(s))localStorage.setItem('mts.selectedSceneId','act1-scene1');const c=localStorage.getItem('mts.characterId');if(c&&!CAST.includes(c))localStorage.removeItem('mts.characterId');try{const x=JSON.parse(localStorage.getItem('mts.lineDetail.current')||'null');if(x&&(!validScene(x.sceneId)||!validLine(x.sceneId,x.lineId)))localStorage.removeItem('mts.lineDetail.current')}catch{localStorage.removeItem('mts.lineDetail.current')}try{const p=JSON.parse(localStorage.getItem('mts.practice.pending')||'null');if(p&&(!validScene(p.sceneId)||(p.lineId&&!validLine(p.sceneId,p.lineId))))localStorage.removeItem('mts.practice.pending')}catch{localStorage.removeItem('mts.practice.pending')}}
function shell(body,active='home'){app.innerHTML=`<main class="shell"><div class="top"><div><div class="eyebrow">Script to Stage · P5</div><div class="brand">The Mousetrap Trainer</div></div><button class="ghost-btn" data-action="role">Role</button></div>${body}</main><nav class="bottom-nav">${[['home','Home'],['script','Script'],['practice','Practice'],['progress','Progress'],['more','More']].map(([r,l])=>`<button data-nav="${r}" class="${active===r?'active':''}">${l}</button>`).join('')}</nav>`;app.querySelectorAll('[data-nav]').forEach(b=>b.onclick=()=>go(`#/${b.dataset.nav}`));const rb=app.querySelector('[data-action=role]');if(rb)rb.onclick=()=>go('#/more')}
function go(h){if(location.hash===h)route();else location.hash=h}
function sceneLabel(id){return EXPECTED.find(x=>x[0]===id)?.[3]||id}function selectedScene(){const x=localStorage.getItem('mts.selectedSceneId');return validScene(x)?x:'act1-scene1'}
function home(){const s=selectedScene();shell(`<section class="card hero"><div class="eyebrow">Continue</div><h1>台本を覚える</h1><p class="muted">Script・Cue Practice・Rehearsal・Progressを1つの状態で接続します。</p><div class="toolbar"><button class="primary-btn" data-open="script">${esc(sceneLabel(s))} を開く</button><button class="ghost-btn" data-open="practice">Practice</button></div></section><section class="grid" style="margin-top:12px">${EXPECTED.map(([id,,,label])=>`<button class="scene-card" data-scene="${id}"><b>${esc(label)}</b><div class="muted">${D.script[id].speeches.length} speeches</div></button>`).join('')}</section>`,'home');app.querySelector('[data-open=script]').onclick=()=>go('#/script');app.querySelector('[data-open=practice]').onclick=()=>go('#/practice');app.querySelectorAll('[data-scene]').forEach(b=>b.onclick=()=>{localStorage.setItem('mts.selectedSceneId',b.dataset.scene);go('#/script')})}
function script(){const scene=selectedScene(),q=new URLSearchParams(location.hash.split('?')[1]||''),focus=q.get('line');const speeches=D.script[scene].speeches;shell(`<section class="card"><div class="eyebrow">Script</div><h2>${esc(sceneLabel(scene))}</h2><div class="toolbar"><button class="ghost-btn" data-scene-picker>Scene</button><button class="ghost-btn">Full</button><button class="ghost-btn">Mine</button><button class="ghost-btn">Cue Focus</button></div></section><section style="margin-top:12px" data-lines>${speeches.map(x=>`<button class="line-row" id="${x.id}" data-line="${x.id}"><span class="speaker">${esc(x.speaker)}</span><span class="line-text">${esc(x.text)}</span></button>`).join('')}</section>`,'script');app.querySelector('[data-scene-picker]').onclick=()=>go('#/scene');app.querySelectorAll('[data-line]').forEach(b=>b.onclick=()=>openLine(scene,b.dataset.line));if(focus&&validLine(scene,focus))setTimeout(()=>document.getElementById(focus)?.scrollIntoView({block:'center'}),0)}
function scene(){shell(`<section class="card"><div class="eyebrow">Scene Navigator</div><h2>Sceneを選択</h2></section><section class="grid" style="margin-top:12px">${EXPECTED.map(([id,,,label])=>`<button class="scene-card" data-open-scene="${id}"><b>${esc(label)}</b><div class="muted">${D.script[id].speeches.length} speeches</div><span class="chip">Open Script</span></button>`).join('')}</section>`,'script');app.querySelectorAll('[data-open-scene]').forEach(b=>b.onclick=()=>{localStorage.setItem('mts.selectedSceneId',b.dataset.openScene);go('#/script')})}
function openLine(scene,line){localStorage.setItem('mts.lineDetail.current',JSON.stringify({sceneId:scene,lineId:line}));$('learningOverlay').hidden=false;location.hash=`#/line?scene=${encodeURIComponent(scene)}&line=${encodeURIComponent(line)}`}
function closeOverlays(){['learningOverlay','cueOverlay','rehearsalOverlay'].forEach(id=>$(id).hidden=true)}
function lineRoute(q){const s=q.get('scene'),l=q.get('line');if(!validLine(s,l)){history.replaceState(null,'','#/script');return route()}localStorage.setItem('mts.selectedSceneId',s);localStorage.setItem('mts.lineDetail.current',JSON.stringify({sceneId:s,lineId:l}));$('learningOverlay').hidden=false;$('learningFrame').contentWindow?.postMessage({type:'mts:line',sceneId:s,lineId:l},'*')}
function practice(){const s=selectedScene(),role=localStorage.getItem('mts.characterId')||'';shell(`<section class="card"><div class="eyebrow">Practice</div><h2>${esc(sceneLabel(s))}</h2><p class="muted">Role: ${esc(role||'未選択')}</p></section><section class="grid" style="margin-top:12px"><button class="mode-btn" data-p="cue"><b>Cue Practice</b><div class="muted">直前Cueから自分の台詞を思い出す</div></button><button class="mode-btn" data-p="rehearsal"><b>Rehearsal</b><div class="muted">通し稽古・TTS・音声認識</div></button></section>`,'practice');app.querySelector('[data-p=cue]').onclick=()=>startPractice('cue',s);app.querySelector('[data-p=rehearsal]').onclick=()=>startPractice('rehearsal',s)}
function startPractice(mode,scene,lineId=''){localStorage.setItem('mts.practice.pending',JSON.stringify({mode,sceneId:scene,lineId}));if(mode==='cue')go(`#/cue?scene=${encodeURIComponent(scene)}${lineId?`&line=${encodeURIComponent(lineId)}`:''}`);else go(`#/rehearsal?scene=${encodeURIComponent(scene)}`)}
function cueRoute(q){const s=validScene(q.get('scene'))?q.get('scene'):selectedScene(),l=q.get('line')||'';if(l&&!validLine(s,l)){history.replaceState(null,'','#/practice');return route()}localStorage.setItem('mts.selectedSceneId',s);localStorage.setItem('mts.practice.pending',JSON.stringify({mode:'cue',sceneId:s,lineId:l}));$('cueOverlay').hidden=false;$('cueFrame').contentWindow?.postMessage({type:'mts:start-cue',sceneId:s,lineId:l},'*')}
function rehearsalRoute(q){const s=validScene(q.get('scene'))?q.get('scene'):selectedScene();localStorage.setItem('mts.selectedSceneId',s);localStorage.setItem('mts.practice.pending',JSON.stringify({mode:'rehearsal',sceneId:s}));$('rehearsalOverlay').hidden=false;$('rehearsalFrame').contentWindow?.postMessage({type:'mts:start-rehearsal',sceneId:s},'*')}
function progress(){let p={};try{p=JSON.parse(localStorage.getItem('mts.sceneProgress')||'{}')}catch{}const a=Number(p['act1-scene1']||0),b=Number(p['act1-scene2']||0),c=Number(p.act2||0),act1=Math.round((a*190+b*336)/526),overall=Math.round((a*190+b*336+c*638)/1164);shell(`<section class="card"><div class="eyebrow">Progress</div><h2>進捗</h2><div class="grid"><div><div class="stat" data-act1>${act1}%</div><div class="muted">Act I</div></div><div><div class="stat" data-act2>${Math.round(c)}%</div><div class="muted">Act II</div></div><div><div class="stat" data-overall>${overall}%</div><div class="muted">Overall</div></div></div></section><section class="card" style="margin-top:12px">${EXPECTED.map(([id,,,label])=>`<p><b>${esc(label)}</b> ${Math.round(Number(p[id]||0))}%</p><div class="progress-bar"><i style="width:${Math.max(0,Math.min(100,Number(p[id]||0)))}%"></i></div>`).join('')}</section>`,'progress')}
function more(){const role=localStorage.getItem('mts.characterId')||'';shell(`<section class="card"><div class="eyebrow">More</div><h2>役を選択</h2><div class="grid">${CAST.map(c=>`<button class="role-btn" data-role="${esc(c)}"><b>${esc(c)}</b>${c===role?'<div class="chip">Selected</div>':''}</button>`).join('')}</div></section>`,'more');app.querySelectorAll('[data-role]').forEach(b=>b.onclick=()=>{localStorage.setItem('mts.characterId',b.dataset.role);toast(`${b.dataset.role} selected`);more()})}
function route(){if(!D)return;closeOverlays();sanitize();const [path,qs='']=location.hash.replace(/^#/,'').split('?'),q=new URLSearchParams(qs);switch(path||'/home'){case'/home':home();break;case'/script':script();break;case'/scene':scene();break;case'/practice':practice();break;case'/progress':progress();break;case'/more':more();break;case'/line':lineRoute(q);break;case'/cue':cueRoute(q);break;case'/rehearsal':rehearsalRoute(q);break;default:history.replaceState(null,'','#/home');home()}}
window.addEventListener('hashchange',route);window.addEventListener('message',e=>{const m=e.data||{};if(m.type==='mts:navigate'){if(m.target==='practice')go('#/practice');if(m.target==='script')go('#/script');if(m.target==='progress')go('#/progress')}if(m.type==='mts:scene-progress-changed'&&location.hash.startsWith('#/progress'))progress()});$('retryBtn').onclick=()=>load().catch(e=>{status.textContent=`FAIL-CLOSED\n${e.message}`});load().catch(e=>{status.textContent=`FAIL-CLOSED\n${e.message}`;status.classList.add('error')});
})();
