(()=>{'use strict';
const CACHE='mts-private-production-v1';
const FILES=['mousetrap_script_data.json','mousetrap_line_translations.json','mousetrap_line_vocabulary.json','mousetrap_line_grammar.json','mousetrap_word_dictionary.json'];
const EXPECTED_SCENES=[['act1-scene1','act1-scene1-speech-',190],['act1-scene2','act1-scene2-speech-',336],['act2','act2-speech-',638]];
const EXPECTED_IDS=EXPECTED_SCENES.flatMap(([sid,prefix,n])=>Array.from({length:n},(_,i)=>prefix+String(i+1).padStart(4,'0'))),IDSET=new Set(EXPECTED_IDS);
let contractPromise=null;
const norm=s=>String(s||'').toLowerCase().trim();
async function digest(bytes){const d=await crypto.subtle.digest('SHA-256',bytes);return [...new Uint8Array(d)].map(x=>x.toString(16).padStart(2,'0')).join('')}
async function contract(){if(contractPromise)return contractPromise;contractPromise=(async()=>{const r=await fetch('pwa-version.json',{cache:'no-store'});if(!r.ok)throw Error(`pwa-version.json: HTTP ${r.status}`);const j=await r.json();if(j?.schemaVersion!==1||!Array.isArray(j.canonicalDataFiles))throw Error('Invalid production data contract');const byName=new Map(j.canonicalDataFiles.map(x=>[String(x.path).split('/').pop(),String(x.sha256||'').toLowerCase()]));for(const n of FILES)if(!/^[0-9a-f]{64}$/.test(byName.get(n)||''))throw Error(`Missing production hash: ${n}`);return{raw:j,byName}})().catch(e=>{contractPromise=null;throw e});return contractPromise}
function exactKeys(v,name){if(!v||typeof v!=='object'||Array.isArray(v))throw Error(`${name}: object required`);const keys=Object.keys(v);const missing=EXPECTED_IDS.filter(id=>!(id in v)),extra=keys.filter(id=>!IDSET.has(id));if(keys.length!==1164||missing.length||extra.length)throw Error(`${name}: speech IDs mismatch`)}
function validateScript(d){if(!d||typeof d!=='object'||Array.isArray(d))throw Error('script: object required');let total=0;for(const [sid,prefix,count] of EXPECTED_SCENES){const a=d[sid]?.speeches;if(!Array.isArray(a)||a.length!==count)throw Error(`script.${sid}: ${a?.length||0}/${count}`);a.forEach((s,i)=>{const expected=prefix+String(i+1).padStart(4,'0');if(s?.id!==expected||!String(s.speaker||'').trim()||!String(s.text||'').trim())throw Error(`script invalid: ${expected}`)});total+=a.length}if(total!==1164)throw Error('script total mismatch');return{speeches:1164,scenes:[190,336,638]}}
function validateTranslations(d){exactKeys(d,'translations');for(const id of EXPECTED_IDS){const x=d[id];if(!x||typeof x!=='object'||!String(x.translation||'').trim()||!String(x.translationSource||'').trim())throw Error(`translation invalid: ${id}`)}return 1164}
function validateVocabulary(d){exactKeys(d,'vocabulary');let count=0;for(const id of EXPECTED_IDS){const a=d[id];if(!Array.isArray(a))throw Error(`vocabulary invalid: ${id}`);for(const x of a){if(!x||typeof x!=='object'||!String(x.surface||'').trim()||!String(x.lemma||'').trim()||!String(x.meaning||'').trim())throw Error(`vocabulary item invalid: ${id}`);count++}}if(count!==1186)throw Error(`vocabulary items ${count}/1186`);return count}
function validateGrammar(d){exactKeys(d,'grammar');let count=0;for(const id of EXPECTED_IDS){const a=d[id];if(!Array.isArray(a))throw Error(`grammar invalid: ${id}`);for(const x of a){if(!x||typeof x!=='object'||!String(x.pattern||'').trim()||!String(x.description||'').trim())throw Error(`grammar item invalid: ${id}`);count++}}if(count!==692)throw Error(`grammar items ${count}/692`);return count}
function validateDictionary(d,vocab){if(!d||typeof d!=='object'||Array.isArray(d))throw Error('dictionary: object required');const keys=Object.keys(d);if(keys.length!==578)throw Error(`dictionary entries ${keys.length}/578`);const lemmas=new Set(keys.map(norm));for(const id of EXPECTED_IDS)for(const v of vocab[id])if(!lemmas.has(norm(v.lemma)))throw Error(`dictionary missing lemma: ${v.lemma}`);for(const k of keys){const x=d[k];if(!x||typeof x!=='object'||!String(x.coreMeaning||'').trim())throw Error(`dictionary invalid: ${k}`)}return 578}
function validateAll(data){const script=validateScript(data['mousetrap_script_data.json']),translations=validateTranslations(data['mousetrap_line_translations.json']),vocabulary=validateVocabulary(data['mousetrap_line_vocabulary.json']),grammar=validateGrammar(data['mousetrap_line_grammar.json']),dictionary=validateDictionary(data['mousetrap_word_dictionary.json'],data['mousetrap_line_vocabulary.json']);return{script,translations,vocabulary,grammar,dictionary}}
function cacheRequest(name){return new Request(new URL(name,location.href).href,{method:'GET'})}
async function getVerifiedResponse(name){if(!FILES.includes(name)||!('caches'in window))return null;const c=await contract(),cache=await caches.open(CACHE),r=await cache.match(cacheRequest(name));if(!r||!r.ok)return null;const bytes=await r.clone().arrayBuffer(),actual=await digest(bytes);if(actual!==c.byName.get(name)){await cache.delete(cacheRequest(name));return null}return new Response(bytes,{status:200,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store','x-mts-private-data':'verified'}})}
async function status(){const c=await contract(),out={complete:true,files:{}};for(const name of FILES){let ok=false,sha256='';try{const cache=await caches.open(CACHE),r=await cache.match(cacheRequest(name));if(r&&r.ok){const b=await r.clone().arrayBuffer();sha256=await digest(b);ok=sha256===c.byName.get(name)}}catch{}out.files[name]={ok,sha256,expected:c.byName.get(name)};if(!ok)out.complete=false}return out}
async function install(fileList){if(!crypto?.subtle||!('caches'in window))throw Error('Private Data Vault is unsupported in this browser');const c=await contract(),map=new Map(Array.from(fileList||[]).map(f=>[f.name,f]));const missing=FILES.filter(n=>!map.has(n));if(missing.length)throw Error(`Required files missing: ${missing.join(', ')}`);const prepared={},parsed={};for(const name of FILES){const f=map.get(name),bytes=await f.arrayBuffer(),actual=await digest(bytes),expected=c.byName.get(name);if(actual!==expected)throw Error(`${name}: SHA-256 mismatch`);let data;try{data=JSON.parse(new TextDecoder().decode(bytes))}catch{throw Error(`${name}: invalid JSON`)}prepared[name]=bytes;parsed[name]=data}const qa=validateAll(parsed),cache=await caches.open(CACHE);for(const name of FILES)await cache.delete(cacheRequest(name));for(const name of FILES){await cache.put(cacheRequest(name),new Response(prepared[name],{status:200,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store','x-mts-private-data':'verified'}}))}return{status:'PASS',cache:CACHE,qa,files:Object.fromEntries(FILES.map(n=>[n,c.byName.get(n)]))}}
async function clear(){if('caches'in window)await caches.delete(CACHE)}
window.MTS_PRIVATE_DATA=Object.freeze({version:1,cacheName:CACHE,files:[...FILES],contract,status,install,clear,getVerifiedResponse,validateAll});
})();
