(()=>{'use strict';
const CONFIG=[
  {frameId:'cueFrame',kind:'cue'},
  {frameId:'rehearsalFrame',kind:'rehearsal'}
];
const q=(doc,sel)=>doc.querySelector(sel);
function route(target){location.hash=target==='home'?'#/home':'#/practice'}
function nativeClose(frame){try{frame.contentDocument?.getElementById('closeBtn')?.click()}catch{}}
function leave(frame,target,{save=true}={}){if(save)nativeClose(frame);setTimeout(()=>route(target),0)}
function button(doc,id,label,aria=label){let b=doc.getElementById(id);if(b)return b;b=doc.createElement('button');b.type='button';b.id=id;b.className='practice-nav-button';b.textContent=label;b.setAttribute('aria-label',aria);return b}
function addStyles(doc){if(doc.getElementById('mtsPracticeNavStyle'))return;const s=doc.createElement('style');s.id='mtsPracticeNavStyle';s.textContent=`
.top{grid-template-columns:44px minmax(0,1fr) auto!important;gap:4px}.practice-nav-top-actions{display:flex;align-items:center;gap:2px}.practice-nav-button{min-height:44px;border:1px solid transparent;border-radius:12px;font:800 13px/1 system-ui,-apple-system,"Noto Sans JP",sans-serif;cursor:pointer}.practice-nav-home{width:44px;background:transparent;color:inherit;font-size:20px}.practice-nav-home:active{background:#ffffff12}.practice-nav-sheet-actions{display:grid;grid-template-columns:1fr 1fr;gap:9px;margin-top:10px}.practice-nav-sheet-actions .practice-nav-button{background:#fff;color:#1e2a3a;border-color:#d7d2c7}.practice-nav-sheet-actions .practice-nav-button[data-primary="true"]{background:#1e2a3a;color:#fff;border-color:#1e2a3a}.practice-nav-inline-home{display:none;flex:1;min-height:46px;background:#fff;color:#1e2a3a;border:1px solid #d7d2c7}.practice-nav-inline-home.show{display:block}.practice-nav-empty-home{margin-left:8px;background:#fff;color:#1e2a3a;border-color:#d7d2c7}.practice-nav-exit{background:#fff!important;color:#1e2a3a!important;border:1px solid #d7d2c7!important}@media(max-width:380px){.practice-nav-sheet-actions{grid-template-columns:1fr}.practice-nav-button{font-size:12px}}
`;doc.head.appendChild(s)}
function currentStored(){return{sceneId:localStorage.getItem('mts.selectedSceneId')||'',character:localStorage.getItem('mts.characterId')||''}}
function hasActive(frame,kind){try{const api=kind==='cue'?frame.contentWindow.MTS008:frame.contentWindow.MTS009;return Number(api?.getState?.()?.total||0)>0}catch{return false}}
function restoreFromSetup(frame,kind){const {sceneId,character}=currentStored();if(!sceneId||!character||!hasActive(frame,kind))return false;try{if(kind==='cue')return !!frame.contentWindow.MTS008?.start?.({sceneId,character});return !!frame.contentWindow.MTS009?.start?.(sceneId,character,false)}catch{return false}}
function setupVisible(doc,kind){const el=doc.getElementById('setup');if(!el)return false;return kind==='cue'?!el.hidden:el.classList.contains('show')}
function cancelSetup(frame,doc,kind){if(restoreFromSetup(frame,kind))return;leave(frame,'practice',{save:false})}
function injectHeader(frame,doc){const top=q(doc,'.top'),close=doc.getElementById('closeBtn'),settings=doc.getElementById('settingsBtn');if(!top||!close||!settings)return;close.textContent='←';close.setAttribute('aria-label','Practiceへ戻る');close.title='Practiceへ戻る';let actions=doc.getElementById('mtsPracticeTopActions');if(!actions){actions=doc.createElement('div');actions.id='mtsPracticeTopActions';actions.className='practice-nav-top-actions';top.insertBefore(actions,settings);const home=button(doc,'homeBtn','⌂','Homeへ戻る');home.classList.add('practice-nav-home');home.title='Home';home.onclick=()=>leave(frame,'home',{save:true});actions.appendChild(home);actions.appendChild(settings)}}
function injectSetup(frame,doc,kind){const setup=doc.getElementById('setup'),sheet=setup?.querySelector(kind==='cue'?'.sheetin':'.sheet');if(!sheet||doc.getElementById('setupNavActions'))return;const row=doc.createElement('div');row.id='setupNavActions';row.className='practice-nav-sheet-actions';const cancel=button(doc,'setupCancelBtn','Cancel','設定を閉じる');cancel.dataset.primary='true';cancel.onclick=()=>cancelSetup(frame,doc,kind);const home=button(doc,'setupHomeBtn','⌂ Home','Homeへ戻る');home.onclick=()=>leave(frame,'home',{save:false});row.append(cancel,home);sheet.appendChild(row)}
function injectGate(frame,doc,kind){const gate=doc.getElementById('dataGate'),sheet=gate?.querySelector(kind==='cue'?'.sheetin':'.sheet');if(!sheet||doc.getElementById('dataGateNavActions'))return;const row=doc.createElement('div');row.id='dataGateNavActions';row.className='practice-nav-sheet-actions';const back=button(doc,'dataGatePracticeBtn','← Practice','Practiceへ戻る');back.dataset.primary='true';back.onclick=()=>leave(frame,'practice',{save:false});const home=button(doc,'dataGateHomeBtn','⌂ Home','Homeへ戻る');home.onclick=()=>leave(frame,'home',{save:false});row.append(back,home);sheet.appendChild(row)}
function injectCueEmpty(frame,doc){const back=doc.getElementById('backPractice');if(!back||doc.getElementById('emptyHomeBtn'))return;const home=button(doc,'emptyHomeBtn','⌂ Home','Homeへ戻る');home.classList.add('practice-nav-empty-home');home.onclick=()=>leave(frame,'home',{save:true});back.insertAdjacentElement('afterend',home)}
function injectPause(frame,doc){const paused=doc.getElementById('paused'),sheet=paused?.querySelector('.sheet');if(!sheet||doc.getElementById('pauseNavActions'))return;const row=doc.createElement('div');row.id='pauseNavActions';row.className='practice-nav-sheet-actions';const exit=button(doc,'pauseExitBtn','← Exit to Practice','練習を終了してPracticeへ戻る');exit.classList.add('practice-nav-exit');exit.onclick=()=>leave(frame,'practice',{save:true});const home=button(doc,'pauseHomeBtn','⌂ Home','Homeへ戻る');home.onclick=()=>leave(frame,'home',{save:true});row.append(exit,home);sheet.appendChild(row)}
function injectCompletion(frame,doc){const actions=q(doc,'.actions'),next=doc.getElementById('nextBtn');if(!actions||!next)return;let home=doc.getElementById('completeHomeBtn');if(!home){home=button(doc,'completeHomeBtn','⌂ Home','Homeへ戻る');home.classList.add('practice-nav-inline-home');home.onclick=()=>leave(frame,'home',{save:true});actions.appendChild(home)}const sync=()=>home.classList.toggle('show',/Back to Practice/i.test(next.textContent||''));sync();new MutationObserver(sync).observe(next,{childList:true,characterData:true,subtree:true})}
function installEscape(frame,doc,kind){if(doc.documentElement.dataset.mtsPracticeNavEscape)return;doc.documentElement.dataset.mtsPracticeNavEscape='1';doc.addEventListener('keydown',ev=>{if(ev.key!=='Escape')return;if(kind==='rehearsal'&&doc.getElementById('paused')?.classList.contains('show')){doc.getElementById('resumeBtn')?.click();ev.preventDefault();return}if(setupVisible(doc,kind)){cancelSetup(frame,doc,kind);ev.preventDefault()}},true)}
function install(frame,kind){let doc;try{doc=frame.contentDocument}catch{return}if(!doc?.documentElement)return;addStyles(doc);injectHeader(frame,doc);injectSetup(frame,doc,kind);injectGate(frame,doc,kind);if(kind==='cue')injectCueEmpty(frame,doc);else{injectPause(frame,doc);injectCompletion(frame,doc)}installEscape(frame,doc,kind);doc.documentElement.dataset.mtsPracticeNavigation='complete'}
function bind({frameId,kind}){const frame=document.getElementById(frameId);if(!frame)return;const run=()=>setTimeout(()=>install(frame,kind),0);frame.addEventListener('load',run);run()}
CONFIG.forEach(bind);
window.MTS_PRACTICE_NAVIGATION=Object.freeze({version:1,installAll:()=>CONFIG.forEach(bind)});
})();
