// Shared study interaction layer, r12: bottom sheets + canonical structure integration.
(()=>{'use strict';
const app=document.getElementById('app');
const lineOverlay=document.getElementById('learningOverlay');
const lineSheet=document.getElementById('learningSheet');
const lineHandle=document.getElementById('learningSheetHandle');
const lineClose=document.getElementById('learningSheetClose');
const learningFrame=document.getElementById('learningFrame');
const wordOverlay=document.getElementById('wordOverlay');
const wordSheet=document.getElementById('wordSheet');
const wordHandle=document.getElementById('wordSheetHandle');
const wordClose=document.getElementById('wordSheetClose');
const wordContent=document.getElementById('wordSheetContent');
const cueFrame=document.getElementById('cueFrame');
const rehearsalFrame=document.getElementById('rehearsalFrame');
if(!app||!lineOverlay||!lineSheet||!lineHandle||!lineClose||!learningFrame||!wordOverlay||!wordSheet||!wordHandle||!wordClose||!wordContent)return;

const KEY={selectedScene:'mts.selectedSceneId',character:'mts.characterId',lineCurrent:'mts.lineDetail.current',readerProgress:'mts.reader.progress',readerLast:'mts.reader.lastPosition',cueState:'mts.practice.cue.state',rehearsalState:'mts.practice.rehearsal.state',cueRatings:'mts.practice.cue.ratings',memoryStages:'mts.memory.stages'};
let restoreWordFocus=null,restoreLineFocus=null,wordTimer=0,lineTimer=0,wordDrag=null,lineDrag=null,enhanceQueued=false,structurePromise=null;
const boundDocs=new WeakSet(),docObservers=new WeakMap();

const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]||c));
const parse=(raw,f=null)=>{try{return raw?JSON.parse(raw):f}catch{return f}};
const scriptData=()=>window.MTS_SHARED_SCRIPT_DATA||null;
const annotations=()=>window.MTS_SHARED_LINE_ANNOTATIONS||null;
const dictionary=()=>window.MTS_SHARED_WORD_DICTIONARY||null;
const speech=(scene,id)=>scriptData()?.[scene]?.speeches?.find(x=>x.id===id)||null;
const annotation=id=>annotations()?.[id]||null;
const norm=v=>String(v||'').trim().toLowerCase();
function dictEntry(lemma){const d=dictionary();if(!d||!lemma)return null;return d[lemma]||d[Object.keys(d).find(k=>norm(k)===norm(lemma))]||null}
function vocabEntry(lineId,lemma,surface){const list=annotation(lineId)?.vocabulary;return Array.isArray(list)?list.find(v=>norm(v.lemma)===norm(lemma)&&(!surface||norm(v.surface)===norm(surface)))||list.find(v=>norm(v.lemma)===norm(lemma))||null:null}
const selectedScene=()=>localStorage.getItem(KEY.selectedScene)||'act1-scene1';
const selectedCharacter=()=>localStorage.getItem(KEY.character)||'';
function previousSpeech(scene,id){const rows=scriptData()?.[scene]?.speeches||[],i=rows.findIndex(x=>x.id===id);return i>0?rows[i-1]:null}
function isWordChar(c){return !!c&&/[A-Za-z0-9'’\-]/.test(c)}
function candidateBoundary(text,start,end,surface){if(!surface)return false;const first=surface[0],last=surface[surface.length-1];if(isWordChar(first)&&isWordChar(text[start-1]))return false;if(isWordChar(last)&&isWordChar(text[end]))return false;return true}

function loadStructure(){
  if(structurePromise)return structurePromise;
  structurePromise=fetch('mousetrap_line_structure.json',{cache:'no-store',credentials:'same-origin'}).then(async r=>{if(!r.ok)throw Error(`STRUCTURE_HTTP_${r.status}`);const d=await r.json();if(d?.schemaVersion!==1||d?.counts?.speeches!==1164||d?.counts?.sentences!==2277||d?.counts?.chunks!==8055)throw Error('STRUCTURE_CONTRACT_INVALID');return d}).catch(e=>{structurePromise=null;console.warn('[MTS] structure unavailable',e);return null});
  return structurePromise;
}

function setCurrent(scene,line){if(!speech(scene,line))return false;localStorage.setItem(KEY.selectedScene,scene);localStorage.setItem(KEY.lineCurrent,JSON.stringify({sceneId:scene,lineId:line}));return true}
function markReaderSeen(scene,id){
  const x=speech(scene,id);if(!x)return;
  const p=parse(localStorage.getItem(KEY.readerProgress),{})||{},role=selectedCharacter();
  p.version=1;p.globalSeen=Array.isArray(p.globalSeen)?p.globalSeen:[];p.roles=p.roles&&typeof p.roles==='object'?p.roles:{};
  if(!p.globalSeen.includes(id))p.globalSeen.push(id);
  if(role&&x.speaker===role){p.roles[role]=Array.isArray(p.roles[role])?p.roles[role]:[];if(!p.roles[role].includes(id))p.roles[role].push(id)}
  const now=new Date().toISOString();p.last={sceneId:scene,lineId:id,role:role||'',updatedAt:now};p.updatedAt=now;localStorage.setItem(KEY.readerProgress,JSON.stringify(p));localStorage.setItem(KEY.readerLast,JSON.stringify(p.last));
}

function makeRanges(text,vocab){const candidates=[],lower=text.toLowerCase();for(const v of vocab){const surface=String(v?.surface||'').trim();if(!surface)continue;const needle=surface.toLowerCase();let from=0;while(from<=lower.length-needle.length){const start=lower.indexOf(needle,from);if(start<0)break;const end=start+needle.length;if(candidateBoundary(text,start,end,surface))candidates.push({start,end,v});from=start+Math.max(1,needle.length)}}candidates.sort((a,b)=>a.start-b.start||(b.end-b.start)-(a.end-a.start));const selected=[];let end=0;for(const c of candidates){if(c.start<end)continue;selected.push(c);end=c.end}return selected}
function clearBinding(el){if(!el)return;delete el.dataset.studyScene;delete el.dataset.studyLine;delete el.dataset.studyFingerprint}
function enhanceTextElement(el,scene,line){
  if(!el)return false;const x=speech(scene,line),a=annotation(line);if(!x||!a)return false;const text=String(x.text||''),fingerprint=`${scene}|${line}|${text}`;
  if(el.textContent!==text){clearBinding(el);return false}if(el.dataset.studyFingerprint===fingerprint)return true;
  const vocab=Array.isArray(a.vocabulary)?a.vocabulary:[],ranges=makeRanges(text,vocab),f=el.ownerDocument.createDocumentFragment();let cursor=0;
  for(const r of ranges){if(r.start>cursor)f.append(el.ownerDocument.createTextNode(text.slice(cursor,r.start)));const span=el.ownerDocument.createElement('span');span.className='reader-vocab';span.dataset.scene=scene;span.dataset.line=line;span.dataset.lemma=String(r.v.lemma||'');span.dataset.surface=String(r.v.surface||text.slice(r.start,r.end));span.textContent=text.slice(r.start,r.end);span.title='辞書を開く';f.append(span);cursor=r.end}
  if(cursor<text.length)f.append(el.ownerDocument.createTextNode(text.slice(cursor)));el.replaceChildren(f);el.dataset.studyScene=scene;el.dataset.studyLine=line;el.dataset.studyFingerprint=fingerprint;return true;
}

function renderWord(scene,line,lemma,surface){
  const x=speech(scene,line),a=annotation(line),v=vocabEntry(line,lemma,surface),d=dictEntry(lemma);if(!x||!a){wordContent.innerHTML='<p class="word-sheet-empty">この単語の文脈情報を読み込めません。</p>';return}
  const display=surface||v?.surface||d?.lemma||lemma||'Word',dl=[];const add=(k,val)=>{if(String(val||'').trim())dl.push(`<dt>${esc(k)}</dt><dd>${esc(val)}</dd>`)};
  add('日本語',d?.contextMeaning||v?.meaning||d?.coreMeaning);add('Core',d?.coreMeaning);add('In this play',d?.contextExplanation);add('Forms',d?.forms);if(d?.pattern)add('Pattern',`${d.pattern}${d.patternDesc?` — ${d.patternDesc}`:''}`);
  wordContent.innerHTML=`<header class="word-sheet-head"><div class="eyebrow">Dictionary</div><h2>${esc(display)}</h2><div class="word-lemma">${esc(d?.lemma||lemma||'')}</div><div class="word-meta">${d?.pos?`<span>${esc(d.pos)}</span>`:''}${d?.ipa?`<span>${esc(d.ipa)}</span>`:''}</div></header><section class="word-dict-card"><div class="label">Word dictionary</div>${dl.length?`<dl class="word-dict-grid">${dl.join('')}</dl>`:'<p class="word-sheet-empty">辞書情報が見つかりません。</p>'}</section><section class="word-context-card"><div class="label">In this line</div><p class="word-context-sentence">${esc(x.text)}</p><p class="word-context-translation">${esc(a.translation||'日本語訳はありません。')}</p></section>`;
}
function openWord(scene,line,lemma,surface,source=null){if(!setCurrent(scene,line))return;clearTimeout(wordTimer);restoreWordFocus=source||document.activeElement;wordOverlay.classList.remove('closing');wordSheet.classList.remove('dragging');wordSheet.style.setProperty('--word-drag','0px');renderWord(scene,line,lemma,surface);wordOverlay.hidden=false;document.body.classList.add('word-sheet-open');wordContent.scrollTop=0}
function finishCloseWord(){wordOverlay.hidden=true;wordOverlay.classList.remove('closing');wordSheet.classList.remove('dragging');wordSheet.style.setProperty('--word-drag','0px');document.body.classList.remove('word-sheet-open');const t=restoreWordFocus;restoreWordFocus=null;if(t?.isConnected)try{t.focus({preventScroll:true})}catch{}}
function closeWord(animate=true){clearTimeout(wordTimer);if(wordOverlay.hidden){finishCloseWord();return}if(!animate){finishCloseWord();return}wordOverlay.classList.add('closing');wordTimer=setTimeout(finishCloseWord,190)}

function sendLine(scene,line){const api=learningFrame.contentWindow?.MTS_LEARNING;if(api?.showLine)api.showLine(scene,line);else learningFrame.contentWindow?.postMessage({type:'mts:line',sceneId:scene,lineId:line},'*')}
function openLine(scene,line,source=null){if(!setCurrent(scene,line))return;markReaderSeen(scene,line);clearTimeout(lineTimer);restoreLineFocus=source||document.activeElement;lineOverlay.classList.remove('closing');lineSheet.classList.remove('dragging');lineSheet.style.setProperty('--sheet-drag','0px');lineOverlay.hidden=false;document.body.classList.add('line-sheet-open');requestAnimationFrame(()=>sendLine(scene,line))}
function finishCloseLine(){lineOverlay.hidden=true;lineOverlay.classList.remove('closing');lineSheet.classList.remove('dragging');lineSheet.style.setProperty('--sheet-drag','0px');document.body.classList.remove('line-sheet-open');const t=restoreLineFocus;restoreLineFocus=null;if(t?.isConnected)try{t.focus({preventScroll:true})}catch{}}
function closeLine(animate=true){clearTimeout(lineTimer);if(lineOverlay.hidden){finishCloseLine();return}if(!animate){finishCloseLine();return}lineOverlay.classList.add('closing');lineTimer=setTimeout(finishCloseLine,210)}

function practiceTheme(kind){const common=`:root{--mts-bg:#f7f5f0;--mts-card:#fff;--mts-ink:#26231f;--mts-muted:#736d65;--mts-line:#ded8cf;--mts-accent:#8b5e3c;--mts-soft:#eee6dc}html,body{background:var(--mts-bg)!important;color:var(--mts-ink)!important}.header{background:linear-gradient(rgba(247,245,240,.98) 82%,rgba(247,245,240,0))!important}.icon{color:var(--mts-ink)!important}.head small,.status{color:var(--mts-muted)!important}.track{background:#e7e0d7!important}.track i{background:var(--mts-accent)!important}.speaker,.kicker{color:var(--mts-accent)!important}.reader-vocab{display:inline!important;padding:0!important;margin:0!important;background:none!important;border:0!important;border-radius:0!important;color:inherit!important;text-decoration-line:underline!important;text-decoration-thickness:1.5px!important;text-underline-offset:3px!important;text-decoration-color:rgba(139,94,60,.86)!important;cursor:pointer!important}.reader-vocab:hover,.reader-vocab:active{background:none!important}[data-study-line]{cursor:pointer}`;
  if(kind==='cue')return common+`.card{background:var(--mts-card)!important;border:1px solid var(--mts-line)!important;box-shadow:0 10px 26px rgba(45,36,29,.07)!important}.cue,.target,.hint,.answer{color:var(--mts-ink)!important}.target{background:#fff!important;border-color:#cfc4b8!important}.target.revealed{background:#f7efe7!important;border-color:#b99a81!important}.question{color:#9b938a!important}.controls{background:rgba(255,255,255,.94)!important;border-top:1px solid var(--mts-line)!important;backdrop-filter:blur(14px)!important}.btn{background:var(--mts-soft)!important;color:var(--mts-ink)!important}.btn.gold{background:var(--mts-accent)!important;color:#fff!important}.sheetin{background:var(--mts-bg)!important;color:var(--mts-ink)!important}.role{border-color:var(--mts-line)!important}.role[aria-pressed=true]{border-color:var(--mts-accent)!important;background:#f3e8de!important}.status{background:#fff!important;border-color:var(--mts-line)!important;color:var(--mts-muted)!important}`;
  return common+`.main{background:var(--mts-bg)!important}.stage{background:var(--mts-card)!important;border:1px solid var(--mts-line)!important;box-shadow:0 12px 30px rgba(45,36,29,.08)!important}.line{color:var(--mts-ink)!important}.line.hiddenline{color:#9b938a!important}.turn{border-top-color:#eee8df!important}.turn small{color:var(--mts-muted)!important}.turn strong{color:var(--mts-ink)!important}.hintbox,.recognition{background:#f3eee8!important;color:var(--mts-ink)!important}.controls{background:rgba(255,255,255,.94)!important;border-top:1px solid var(--mts-line)!important;backdrop-filter:blur(14px)!important}.ctl,.next{background:var(--mts-soft)!important;color:var(--mts-ink)!important}.ctl.primary,.reveal{background:var(--mts-accent)!important;color:#fff!important}.sheet{background:var(--mts-bg)!important;color:var(--mts-ink)!important}.role{border-color:var(--mts-line)!important}.role[aria-pressed=true]{border-color:var(--mts-accent)!important;background:#f3e8de!important}.statusbox{border-color:var(--mts-line)!important;color:var(--mts-muted)!important}`;
}
function injectPracticeStyle(doc,kind){let s=doc.getElementById('mts-study-anywhere-style');if(!s){s=doc.createElement('style');s.id='mts-study-anywhere-style';doc.head.appendChild(s)}s.textContent=practiceTheme(kind)}

function cueContext(){const scene=selectedScene(),character=selectedCharacter(),all=parse(localStorage.getItem(KEY.cueState),{})||{},state=all[`${scene}|${character}`]||{},targetId=state.speechId||'';if(!targetId||!speech(scene,targetId))return null;const cue=previousSpeech(scene,targetId);return{scene,targetId,cueId:cue?.id||'',hintLevel:Number(state.hintLevel)||0,revealed:!!state.revealed}}
function rehearsalContext(){const scene=selectedScene(),character=selectedCharacter(),all=parse(localStorage.getItem(KEY.rehearsalState),{})||{},state=all[`${scene}|${character}`]||{},lineId=state.speechId||'';return lineId&&speech(scene,lineId)?{scene,lineId,hintLevel:Number(state.hintLevel)||0,revealed:!!state.revealed,character}:null}
function maskChars(text,mode){let kept=false;return String(text).replace(/[A-Za-z0-9]/g,ch=>{if(mode===2&&!kept){kept=true;return ch}return '•'})}
function maskLine(text,line,level){if(!line?.sentences?.length)return text;let out='',cursor=0;for(const s of line.sentences){if(s.start>cursor)out+=text.slice(cursor,s.start);const sentence=text.slice(s.start,s.end);let sc=0;for(let i=0;i<s.chunks.length;i++){const c=s.chunks[i];if(c.start>sc)out+=sentence.slice(sc,c.start);const part=sentence.slice(c.start,c.end);if(level===1){const hide=s.chunks.length===1||i%2===1;out+=hide?maskChars(part,3):part}else if(level===2)out+=maskChars(part,2);else out+=maskChars(part,3);sc=c.end}if(sc<sentence.length)out+=sentence.slice(sc);cursor=s.end}if(cursor<text.length)out+=text.slice(cursor);return out}
async function applyPracticeHint(doc,kind){const structure=await loadStructure();if(!structure)return;if(kind==='cue'){const c=cueContext();if(!c||c.revealed||c.hintLevel<1)return;const el=doc.getElementById('answerContent'),x=speech(c.scene,c.targetId),line=structure.lines?.[c.targetId];if(el&&x&&line){const masked=maskLine(x.text,line,Math.min(3,c.hintLevel));if(el.textContent!==masked){el.className='hint';el.textContent=masked}}}else{const c=rehearsalContext();if(!c||c.revealed||c.hintLevel<1)return;const box=doc.getElementById('hintBox'),x=speech(c.scene,c.lineId),line=structure.lines?.[c.lineId];if(box&&x&&line){const masked=maskLine(x.text,line,Math.min(3,c.hintLevel));if(box.textContent!==masked){box.textContent=masked;box.classList.add('show')}}}}
function enhancePracticeDoc(doc,kind){if(!doc||!scriptData()||!annotations())return;injectPracticeStyle(doc,kind);if(kind==='cue'){const c=cueContext();if(c){if(c.cueId)enhanceTextElement(doc.getElementById('cueText'),c.scene,c.cueId);enhanceTextElement(doc.getElementById('answerContent'),c.scene,c.targetId)}}else{const c=rehearsalContext();if(c)enhanceTextElement(doc.getElementById('line'),c.scene,c.lineId)}applyPracticeHint(doc,kind)}
function bindPracticeFrame(frame,kind){if(!frame)return;let doc;try{doc=frame.contentDocument}catch{return}if(!doc)return;injectPracticeStyle(doc,kind);if(!boundDocs.has(doc)){boundDocs.add(doc);doc.addEventListener('click',event=>{const target=event.target?.closest?event.target:null;if(!target)return;const word=target.closest('.reader-vocab');if(word){event.preventDefault();event.stopPropagation();event.stopImmediatePropagation();openWord(word.dataset.scene,word.dataset.line,word.dataset.lemma,word.dataset.surface,word);return}const line=target.closest('[data-study-line][data-study-scene]');if(!line)return;event.preventDefault();event.stopPropagation();event.stopImmediatePropagation();openLine(line.dataset.studyScene,line.dataset.studyLine,line)},true);const ob=new MutationObserver(()=>enhancePracticeDoc(doc,kind));ob.observe(doc.documentElement,{childList:true,subtree:true,characterData:true});docObservers.set(doc,ob)}enhancePracticeDoc(doc,kind)}
function enhanceMain(){enhanceQueued=false;if(!scriptData()||!annotations())return;if(location.hash.startsWith('#/script')){const scene=selectedScene();app.querySelectorAll('.line-row[data-line]').forEach(row=>enhanceTextElement(row.querySelector('.line-text'),scene,row.dataset.line))}if(location.hash.startsWith('#/search'))app.querySelectorAll('.search-result[data-search-line][data-search-scene]').forEach(row=>enhanceTextElement(row.querySelector('.search-line'),row.dataset.searchScene,row.dataset.searchLine))}
function queueEnhance(){if(enhanceQueued)return;enhanceQueued=true;requestAnimationFrame(()=>{enhanceMain();bindPracticeFrame(cueFrame,'cue');bindPracticeFrame(rehearsalFrame,'rehearsal')})}

function interceptMain(event){const target=event.target?.closest?event.target:null;if(!target)return;const word=target.closest('.reader-vocab');if(word){event.preventDefault();event.stopPropagation();event.stopImmediatePropagation();openWord(word.dataset.scene,word.dataset.line,word.dataset.lemma,word.dataset.surface,word);return}if(location.hash.startsWith('#/script')){const row=target.closest('.line-row[data-line]');if(row){event.preventDefault();event.stopPropagation();event.stopImmediatePropagation();openLine(selectedScene(),row.dataset.line,row);return}}if(location.hash.startsWith('#/search')){const row=target.closest('.search-result[data-search-line][data-search-scene]');if(row){event.preventDefault();event.stopPropagation();event.stopImmediatePropagation();openLine(row.dataset.searchScene,row.dataset.searchLine,row)}}}
document.addEventListener('click',interceptMain,true);

function endWordDrag(event){if(!wordDrag||event.pointerId!==wordDrag.id)return;const dy=Math.max(0,event.clientY-wordDrag.y),dt=Math.max(1,performance.now()-wordDrag.t),v=dy/dt;wordDrag=null;wordSheet.classList.remove('dragging');if(dy>86||v>.62)closeWord();else wordSheet.style.setProperty('--word-drag','0px')}
wordHandle.addEventListener('pointerdown',e=>{if(e.target?.closest?.('button'))return;wordDrag={id:e.pointerId,y:e.clientY,t:performance.now()};wordSheet.classList.add('dragging');try{wordHandle.setPointerCapture(e.pointerId)}catch{}});wordHandle.addEventListener('pointermove',e=>{if(wordDrag&&e.pointerId===wordDrag.id)wordSheet.style.setProperty('--word-drag',`${Math.max(0,e.clientY-wordDrag.y)}px`)});wordHandle.addEventListener('pointerup',endWordDrag);wordHandle.addEventListener('pointercancel',endWordDrag);wordClose.addEventListener('click',()=>closeWord());wordOverlay.addEventListener('click',e=>{if(e.target===wordOverlay)closeWord()});
function endLineDrag(event){if(!lineDrag||event.pointerId!==lineDrag.id)return;const dy=Math.max(0,event.clientY-lineDrag.y),dt=Math.max(1,performance.now()-lineDrag.t),v=dy/dt;lineDrag=null;lineSheet.classList.remove('dragging');if(dy>90||v>.65)closeLine();else lineSheet.style.setProperty('--sheet-drag','0px')}
lineHandle.addEventListener('pointerdown',e=>{if(e.target?.closest?.('button'))return;lineDrag={id:e.pointerId,y:e.clientY,t:performance.now()};lineSheet.classList.add('dragging');try{lineHandle.setPointerCapture(e.pointerId)}catch{}});lineHandle.addEventListener('pointermove',e=>{if(lineDrag&&e.pointerId===lineDrag.id)lineSheet.style.setProperty('--sheet-drag',`${Math.max(0,e.clientY-lineDrag.y)}px`)});lineHandle.addEventListener('pointerup',endLineDrag);lineHandle.addEventListener('pointercancel',endLineDrag);lineClose.addEventListener('click',()=>closeLine());lineOverlay.addEventListener('click',e=>{if(e.target===lineOverlay)closeLine()});

document.addEventListener('keydown',e=>{if(e.key!=='Escape')return;if(!wordOverlay.hidden){e.preventDefault();closeWord();return}if(!lineOverlay.hidden){e.preventDefault();closeLine()}});
window.addEventListener('message',e=>{const m=e.data||{};if(e.source!==learningFrame.contentWindow)return;if(m.type==='mts:open-word'){openWord(m.sceneId,m.lineId,m.lemma,m.surface,learningFrame);return}if(m.type==='mts:start-practice'){if(!['cue','rehearsal'].includes(m.mode))return;localStorage.setItem('mts.practice.pending',JSON.stringify({mode:m.mode,sceneId:m.sceneId,lineId:m.lineId}));closeLine(false);location.hash=`#/${m.mode}?scene=${encodeURIComponent(m.sceneId)}&line=${encodeURIComponent(m.lineId)}`}});

function syncMemoryStages(){const ratings=parse(localStorage.getItem(KEY.cueRatings),{})||{},state=parse(localStorage.getItem(KEY.memoryStages),{})||{};let changed=false;for(const [id,r] of Object.entries(ratings)){if(!r?.updatedAt||state[id]?.ratingUpdate===r.updatedAt)continue;let stage=Number(state[id]?.stage)||0;if(r.rating==='good'||r.last==='good')stage=Math.min(3,stage+1);else if(r.rating==='again'||r.last==='again')stage=Math.max(0,stage-1);state[id]={stage,ratingUpdate:r.updatedAt};changed=true}if(changed)localStorage.setItem(KEY.memoryStages,JSON.stringify(state))}

new MutationObserver(queueEnhance).observe(app,{childList:true,subtree:true});
window.addEventListener('storage',e=>{if([KEY.cueState,KEY.rehearsalState,KEY.cueRatings].includes(e.key)){syncMemoryStages();queueEnhance()}});
window.addEventListener('hashchange',()=>{if(!location.hash.startsWith('#/script')&&!location.hash.startsWith('#/search')&&!location.hash.startsWith('#/cue')&&!location.hash.startsWith('#/rehearsal')){closeWord(false);closeLine(false)}else if(location.hash.startsWith('#/cue')||location.hash.startsWith('#/rehearsal'))closeWord(false);queueEnhance()});
for(const [frame,kind] of [[cueFrame,'cue'],[rehearsalFrame,'rehearsal']])if(frame){frame.addEventListener('load',()=>bindPracticeFrame(frame,kind));setTimeout(()=>bindPracticeFrame(frame,kind),0)}
loadStructure();syncMemoryStages();queueEnhance();
window.MTS_STUDY_ANYWHERE=Object.freeze({enhance:queueEnhance,openWord,closeWord,openLine,closeLine,loadStructure});window.MTS_READER_V2=window.MTS_STUDY_ANYWHERE;
})();
