// canonical-study-ui-v1
const {test,expect}=require('@playwright/test');
const BASE='http://127.0.0.1:4173/index.html';
async function ready(page){await page.goto(BASE,{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>window.MTS_INDEX_ZERO?.store?.hasCore?.(),null,{timeout:12000});await page.evaluate(()=>Promise.all([MTS_INDEX_ZERO.store.loadStudy(),MTS_INDEX_ZERO.store.loadStructure()]));await page.waitForFunction(()=>MTS_INDEX_ZERO.store.hasStudy()&&MTS_INDEX_ZERO.store.hasStructure(),null,{timeout:15000})}

test('neutral-only vocabulary never enters line presentation while play meanings do',async({page})=>{await ready(page);const sample=await page.evaluate(()=>{for(const scene of ['act1-scene1','act1-scene2','act2'])for(const speech of MTS_INDEX_ZERO.store.getScene(scene)){const all=MTS_INDEX_ZERO.store.getVocabularyAll(speech.id),shown=MTS_INDEX_ZERO.store.getVocabulary(speech.id);const hidden=all.find(x=>x.playMeaning===false);if(hidden)return{scene,line:speech.id,hiddenSurface:hidden.surface,shown:shown.length}}return null});expect(sample).toBeTruthy();await page.goto(`${BASE}#/line?scene=${sample.scene}&line=${sample.line}`);await page.waitForFunction(()=>MTS_INDEX_ZERO.store.hasStudy());const rows=page.locator('.word-row');await expect(rows).toHaveCount(sample.shown);if(sample.shown===0)await expect(page.getByRole('heading',{name:'Vocabulary'})).toHaveCount(0);const highlighted=await page.locator('.vocab-inline').allTextContents();expect(highlighted.map(x=>x.toLowerCase())).not.toContain(String(sample.hiddenSurface).toLowerCase())});

test('line with no play vocabulary has no Vocabulary section or highlight',async({page})=>{await ready(page);const sample=await page.evaluate(()=>{for(const scene of ['act1-scene1','act1-scene2','act2'])for(const speech of MTS_INDEX_ZERO.store.getScene(scene))if(MTS_INDEX_ZERO.store.getVocabulary(speech.id).length===0)return{scene,line:speech.id};return null});expect(sample).toBeTruthy();await page.goto(`${BASE}#/line?scene=${sample.scene}&line=${sample.line}`);await expect(page.getByRole('heading',{name:'Vocabulary'})).toHaveCount(0);await expect(page.locator('.word-row')).toHaveCount(0);await expect(page.locator('.line-detail-text .vocab-inline')).toHaveCount(0)});

test('Structure renders chunking-v1 markers and clause hierarchy without legacy role/type',async({page})=>{await ready(page);const sample=await page.evaluate(()=>{for(const scene of ['act1-scene1','act1-scene2','act2'])for(const speech of MTS_INDEX_ZERO.store.getScene(scene)){const s=MTS_INDEX_ZERO.store.getStructure(speech.id);if(s?.sentences?.some(x=>x.clauses?.length&&x.chunks?.some(c=>/^S\d/.test(c.marker))&&x.chunks?.some(c=>c.marker==='HV')))return{scene,line:speech.id}}return null});expect(sample).toBeTruthy();await page.goto(`${BASE}#/line?scene=${sample.scene}&line=${sample.line}`);await page.locator('.structure-summary').click();await expect(page.locator('[data-clause-marker]').first()).toBeVisible();await expect(page.locator('[data-marker="HV"]').first()).toBeVisible();await expect(page.locator('[data-marker^="S"]').first()).toBeVisible();await expect(page.getByText('S / V / O / C / M',{exact:true})).toHaveCount(0);await expect(page.getByText('undefined',{exact:true})).toHaveCount(0);await page.locator('[data-marker="HV"]').first().click();await expect(page.locator('.structure-info:not([hidden])')).toContainText('HV')});
