const {test,expect}=require('@playwright/test');
test.beforeEach(async({page})=>{await page.goto('http://127.0.0.1:4173/index.html');await expect(page.locator('#dataGate')).toBeHidden();});
test('production-path HTTP resources and canonical gate',async({page})=>{const qa=await page.evaluate(()=>window.MTS_P5_QA);expect(qa).toEqual({status:'PASS',speeches:1164,scenes:[190,336,638],vocabulary:1186,grammar:692,dictionary:578});});
test('core navigation and line detail',async({page})=>{await page.getByRole('button',{name:/Act I · Scene I を開く/}).click();await expect(page).toHaveURL(/#\/script/);await page.locator('[data-line]').first().click();await expect(page).toHaveURL(/#\/line\?/);await expect(page.locator('#learningOverlay')).toBeVisible();await page.goBack();await expect(page).toHaveURL(/#\/script/);});
test('practice route keeps exact pending line',async({page})=>{await page.goto('http://127.0.0.1:4173/index.html#/script');await expect(page.locator('#dataGate')).toBeHidden();const id=await page.locator('[data-line]').nth(5).getAttribute('data-line');await page.locator('[data-line]').nth(5).click();await page.frameLocator('#learningFrame').getByRole('button',{name:'Cue Practice'}).click();await expect(page).toHaveURL(/#\/cue\?/);const p=await page.evaluate(()=>JSON.parse(localStorage.getItem('mts.practice.pending')));expect(p.lineId).toBe(id);});
test('progress weighting',async({page})=>{await page.evaluate(()=>localStorage.setItem('mts.sceneProgress',JSON.stringify({'act1-scene1':100,'act1-scene2':50,'act2':25})));await page.goto('http://127.0.0.1:4173/index.html#/progress');await expect(page.locator('#dataGate')).toBeHidden();await expect(page.locator('[data-act1]')).toHaveText('68%');await expect(page.locator('[data-overall]')).toHaveText('44%');});
test('stale state sanitization',async({page})=>{await page.evaluate(()=>{localStorage.setItem('mts.selectedSceneId','BAD');localStorage.setItem('mts.characterId','BAD');localStorage.setItem('mts.lineDetail.current','{"sceneId":"bad","lineId":"bad"}');});await page.reload();await expect(page.locator('#dataGate')).toBeHidden();expect(await page.evaluate(()=>localStorage.getItem('mts.selectedSceneId'))).toBe('act1-scene1');expect(await page.evaluate(()=>localStorage.getItem('mts.characterId'))).toBeNull();});
test('fail closed malformed canonical',async({browser})=>{const context=await browser.newContext();const p=await context.newPage();await p.route('**/mousetrap_script_data.json',async route=>{const r=await route.fetch();const d=await r.json();d.act2.speeches.pop();await route.fulfill({status:200,contentType:'application/json',body:JSON.stringify(d)});});await p.goto('http://127.0.0.1:4173/index.html');await expect(p.locator('#dataGate')).toBeVisible();await expect(p.locator('#gateStatus')).toContainText('FAIL-CLOSED');await context.close();});
test('browser APIs capability/fallback',async({page})=>{const caps=await page.evaluate(()=>({tts:'speechSynthesis'in window,rec:!!(window.SpeechRecognition||window.webkitSpeechRecognition)}));expect(typeof caps.tts).toBe('boolean');expect(typeof caps.rec).toBe('boolean');});
