const {test,expect}=require('@playwright/test');
const BASE='http://127.0.0.1:4173/index.html';
async function controlled(page){
  await page.goto(BASE,{waitUntil:'domcontentloaded'});
  await expect(page.locator('#dataGate')).toBeHidden();
  await page.evaluate(()=>navigator.serviceWorker.ready.then(()=>true));
  await page.waitForFunction(()=>!!navigator.serviceWorker.controller,null,{timeout:5000});
  await expect(page.locator('#dataGate')).toBeHidden();
}
test('manifest, icons and production metadata are reachable',async({page})=>{await controlled(page);const result=await page.evaluate(async()=>{const m=await (await fetch('manifest.webmanifest')).json();const v=await (await fetch('pwa-version.json')).json();const icons=await Promise.all(m.icons.map(async x=>({src:x.src,status:(await fetch(x.src)).status})));return {m,v,icons}});expect(result.m.display).toBe('standalone');expect(result.m.start_url).toBe('./index.html');expect(result.icons.every(x=>x.status===200)).toBe(true);expect(result.v.buildId).toBe('p6-2026-08-24-r1')});
test('service worker is active and reports compatible build/data versions',async({page})=>{await controlled(page);const version=await page.evaluate(()=>new Promise(resolve=>{const timer=setTimeout(()=>resolve(null),3000);const handler=e=>{if(e.data?.type==='MTS_PWA_VERSION'){clearTimeout(timer);navigator.serviceWorker.removeEventListener('message',handler);resolve(e.data)}};navigator.serviceWorker.addEventListener('message',handler);navigator.serviceWorker.controller.postMessage({type:'GET_VERSION'})}));expect(version).toEqual({type:'MTS_PWA_VERSION',buildId:'p6-2026-08-24-r1',dataVersion:'p5-canonical-freeze-2026-08-24-r1'})});
test('offline reload keeps app shell, canonical data and P5 navigation usable',async({page,context})=>{await controlled(page);await page.goto(BASE+'#/script');await expect(page.locator('#dataGate')).toBeHidden();await context.setOffline(true);await page.reload();await expect(page.locator('#dataGate')).toBeHidden();await expect(page.locator('[data-line]').first()).toBeVisible();await page.locator('[data-line]').first().click();await expect(page).toHaveURL(/#\/line\?/);await expect(page.locator('#learningOverlay')).toBeVisible();await page.goBack();await page.goto(BASE+'#/practice');await page.getByRole('button',{name:'Cue Practice'}).first().click();await expect(page).toHaveURL(/#\/cue/);await page.goto(BASE+'#/practice');await page.getByRole('button',{name:'Rehearsal'}).first().click();await expect(page).toHaveURL(/#\/rehearsal/);await page.goto(BASE+'#/progress');await expect(page.getByText('進捗')).toBeVisible()});
test('local persistence survives offline reload',async({page,context})=>{await controlled(page);await page.evaluate(()=>{localStorage.setItem('mts.selectedSceneId','act1-scene2');localStorage.setItem('mts.characterId','MOLLIE');localStorage.setItem('mts.sceneProgress',JSON.stringify({'act1-scene1':44,'act1-scene2':55,'act2':66}));localStorage.setItem('mts.practice.rehearsal.state',JSON.stringify({sceneId:'act1-scene1',index:12,paused:true}))});await context.setOffline(true);await page.reload();await expect(page.locator('#dataGate')).toBeHidden();const persisted=await page.evaluate(()=>({scene:localStorage.getItem('mts.selectedSceneId'),role:localStorage.getItem('mts.characterId'),progress:localStorage.getItem('mts.sceneProgress'),rehearsal:localStorage.getItem('mts.practice.rehearsal.state')}));expect(persisted.scene).toBe('act1-scene2');expect(persisted.role).toBe('MOLLIE');expect(JSON.parse(persisted.progress).act2).toBe(66);expect(JSON.parse(persisted.rehearsal).paused).toBe(true)});
test('stale PWA caches are cleaned on a fresh activation without touching localStorage',async({page})=>{await controlled(page);await page.evaluate(async()=>{localStorage.setItem('mts.characterId','GILES');await caches.open('mts-pwa-shell-stale-build');await caches.open('mts-pwa-data-stale-data');const reg=await navigator.serviceWorker.getRegistration();await reg.unregister()});await page.reload();await page.evaluate(()=>navigator.serviceWorker.ready.then(()=>true));await page.waitForFunction(()=>!!navigator.serviceWorker.controller,null,{timeout:5000});await expect.poll(async()=>page.evaluate(async()=>!(await caches.keys()).includes('mts-pwa-shell-stale-build')&&!(await caches.keys()).includes('mts-pwa-data-stale-data'))).toBe(true);expect(await page.evaluate(()=>localStorage.getItem('mts.characterId'))).toBe('GILES')});
test('corrupted canonical cache fails closed offline instead of serving stale data',async({page,context})=>{await controlled(page);const dataCache=await page.evaluate(async()=>(await caches.keys()).find(x=>x.startsWith('mts-pwa-data-')));expect(dataCache).toBeTruthy();await page.evaluate(async name=>{const c=await caches.open(name);await c.put('./mousetrap_line_grammar.json',new Response('{"corrupt":true}',{headers:{'content-type':'application/json'}}))},dataCache);await context.setOffline(true);await page.reload();await expect(page.locator('#dataGate')).toBeVisible();await expect(page.locator('#gateStatus')).toContainText('FAIL-CLOSED')});
test('missing app-shell cache returns explicit offline fallback, not a blank page',async({page,context})=>{await controlled(page);await page.evaluate(async()=>{const name=(await caches.keys()).find(x=>x.startsWith('mts-pwa-shell-'));const c=await caches.open(name);await c.delete('./index.html')});await context.setOffline(true);await page.reload();await expect(page.getByRole('heading',{name:'Offline'})).toBeVisible()});
