import fs from 'node:fs';import path from 'node:path';import vm from 'node:vm';import {spawnSync} from 'node:child_process';
const cwd=process.cwd(),read=p=>fs.readFileSync(path.join(cwd,p),'utf8'),exists=p=>fs.existsSync(path.join(cwd,p)),fail=m=>{throw new Error(m)};
const syntaxCheck=p=>{const r=spawnSync(process.execPath,['--check',p],{cwd,encoding:'utf8'});if(r.status!==0)fail(`${p} syntax failed: ${r.stderr||r.stdout}`)};
const pngDimensions=p=>{const b=fs.readFileSync(path.join(cwd,p));if(b.length<24||b.toString('hex',0,8)!=='89504e470d0a1a0a')fail(`invalid PNG ${p}`);return[b.readUInt32BE(16),b.readUInt32BE(20)]};

const manifest=JSON.parse(read('manifest.webmanifest'));for(const k of ['name','short_name','start_url','scope','display','background_color','theme_color','icons'])if(!manifest[k])fail(`manifest missing ${k}`);if(manifest.display!=='standalone')fail('manifest display must be standalone');const declared=new Map(manifest.icons.map(i=>[i.src,i]));for(const [src,size] of [['icons/icon-192.png',192],['icons/icon-512.png',512],['icons/icon-maskable-512.png',512]]){if(!declared.has(src)||!exists(src))fail(`missing icon ${src}`);const [w,h]=pngDimensions(src);if(w!==size||h!==size)fail(`icon dimensions ${src}: ${w}x${h}`)}

const version=JSON.parse(read('pwa-version.json'));if(version.schemaVersion!==1||version.buildId!=='p6-2026-08-25-r12'||!version.dataVersion)fail('pwa-version invalid');if(!Array.isArray(version.canonicalDataFiles)||version.canonicalDataFiles.length!==5)fail('canonical contract must contain five files');const expected=new Set(['mousetrap_script_data.json','mousetrap_line_translations.json','mousetrap_line_vocabulary.json','mousetrap_line_grammar.json','mousetrap_word_dictionary.json']);for(const f of version.canonicalDataFiles){if(!expected.delete(f.path)||!/^[0-9a-f]{64}$/.test(f.sha256))fail(`bad canonical entry ${f.path}`)}if(expected.size)fail(`missing canonical files ${[...expected].join(',')}`);if(version.derivedRuntimeData?.[0]?.path!=='mousetrap_line_structure.json')fail('derived structure contract missing');

const html=read('index.html');for(const t of ['src="reader_sheet.js"','id="learningOverlay"','id="learningSheet"','id="learningSheetHandle"','id="learningSheetClose"','id="learningFrame"','id="wordOverlay"','id="wordSheet"','id="cueFrame"','id="rehearsalFrame"'])if(!html.includes(t))fail(`index missing ${t}`);if(html.includes('Full line explanation page'))fail('legacy dedicated line-page wording remains');if(/https?:\/\/|cdn\./i.test(html))fail('index contains external runtime dependency');

const required=['index.html','p5.css','p5_app.js','reader_sheet.js','p6_private_data.js','pages_private_import.js','p6_pwa.css','p6_pwa.js','P2_learning.html','008_cue_practice_P3.html','009_rehearsal_P4.html','mousetrap_line_structure.json','manifest.webmanifest','pwa-version.json','offline.html','sw.js','scripts/assemble-production.mjs','scripts/build-learning-structure.mjs'];for(const f of required)if(!exists(f))fail(`missing required asset ${f}`);

syntaxCheck('reader_sheet.js');syntaxCheck('sw.js');syntaxCheck('scripts/build-learning-structure.mjs');syntaxCheck('scripts/assemble-production.mjs');new vm.Script(read('p6_private_data.js'),{filename:'p6_private_data.js'});new vm.Script(read('p5_app.js'),{filename:'p5_app.js'});

const structure=JSON.parse(read('mousetrap_line_structure.json'));if(structure.schemaVersion!==1||!structure.copyrightSafe)fail('structure schema/copyright contract invalid');if(structure.counts?.speeches!==1164||structure.counts?.sentences!==2277||structure.counts?.chunks!==8055)fail('structure global counts invalid');const roles=new Set(['S','V','O','C','M',"S'","V'","O'","C'"]),types=new Set(['NP','VP','PP','AdvP','AdjP','NC','AC','AdvC','Inf','Gerund','Participle','PhrasalVerb','FixedExpression']);const lines=Object.entries(structure.lines||{});if(lines.length!==1164)fail(`structure lines ${lines.length}/1164`);let sc=0,cc=0;for(const [id,line] of lines){if(!Array.isArray(line.sentences)||!line.sentences.length)fail(`structure line empty ${id}`);let speechCursor=0;for(const s of line.sentences){if(!Number.isInteger(s.start)||!Number.isInteger(s.end)||s.start<speechCursor||s.end<=s.start)fail(`bad sentence span ${s.id}`);speechCursor=s.end;let ccur=0;if(!Array.isArray(s.chunks)||!s.chunks.length)fail(`empty chunks ${s.id}`);for(const c of s.chunks){if(c.start!==ccur||c.end<=c.start)fail(`chunk coverage ${c.id}`);if(!roles.has(c.role)||!types.has(c.type))fail(`chunk label ${c.id}`);if('text'in c)fail(`structure duplicates source text ${c.id}`);ccur=c.end;cc++}if(ccur!==s.end-s.start)fail(`sentence reconstruction length ${s.id}`);sc++}}if(sc!==2277||cc!==8055)fail(`structure item counts ${sc}/2277 ${cc}/8055`);if(Object.keys(structure.characters||{}).length!==9)fail('character registry must contain 9 speakers');

const sheet=read('reader_sheet.js');for(const t of ['openLine','closeLine','openWord','maskLine','MTS_STUDY_ANYWHERE','mousetrap_line_structure.json','learningSheetHandle','wordSheetHandle','data-study-line','cueState','rehearsalState','memoryStages'])if(!sheet.includes(t))fail(`study layer missing ${t}`);if(!sheet.includes('background:none!important'))fail('underline-only vocabulary styling missing');for(const legacy of ['linear-gradient(to top,rgba(232,190,97','.reader-vocab:active{background:rgba'])if(sheet.includes(legacy))fail(`legacy vocabulary highlight remains ${legacy}`);

const p2=read('P2_learning.html');for(const t of ['Structure','S / V / O / C / M','詳しく見る','Grammar / Usage','mousetrap_line_structure.json','mts:open-word','mts:start-practice','struct-chunk','chunk-info','float-nav'])if(!p2.includes(t))fail(`Line sheet UI missing ${t}`);for(const legacy of ['setParentLine(','parent.location.hash=`#/line'])if(p2.includes(legacy))fail(`dedicated line navigation remains ${legacy}`);

const sw=read('sw.js');for(const t of [version.buildId,version.dataVersion,'mousetrap_line_structure.json','reader_sheet.js','skipWaiting','clients.claim','DATA_HASH_MISMATCH'])if(!sw.includes(t))fail(`sw missing ${t}`);
const resolver=read('p6_private_data.js');for(const t of ['version:3','getVerifiedResponse','validateAll','1186','692','578','UNVERIFIED_CANONICAL_FETCH_BLOCKED'])if(!resolver.includes(t))fail(`resolver missing ${t}`);
const p5=read('p5_app.js');for(const t of ['mts.reader.progress','mts.practice.cue.ratings','MTS_SHARED_LINE_ANNOTATIONS','MTS_SHARED_WORD_DICTIONARY','#/search'])if(!p5.includes(t))fail(`p5 invariant missing ${t}`);
const builder=read('scripts/build-learning-structure.mjs');for(const t of ['2277','8055','003-03A0_CORRECTION_U0053.txt','copyrightSafe','speech-local sentences','010_CHARACTER_INDEX.txt'])if(!builder.includes(t))fail(`structure builder missing ${t}`);

const productionRuntime=['index.html','p5_app.js','reader_sheet.js','p6_private_data.js','p6_pwa.js','P2_learning.html','008_cue_practice_P3.html','009_rehearsal_P4.html','sw.js'];const unresolved=/\b(?:TODO|FIXME|coming soon|not implemented|placeholder|dummy|fake|temporary)\b/i;for(const f of productionRuntime){const src=read(f).replace(/\bplaceholder\s*=\s*(["']).*?\1/gi,'');if(unresolved.test(src))fail(`blocking marker in ${f}`)}
console.log(JSON.stringify({status:'PASS',buildId:version.buildId,canonicalContract:5,derivedStructure:true,structureCounts:{speeches:1164,sentences:2277,chunks:8055},lineBottomSheet:true,dictionaryBottomSheet:true,underlineOnlyVocabulary:true,structureDiagram:true,normalDetailedDisclosure:true,practiceChunkHints:true,practiceStudyAnywhere:true,characterRegistry:true,serviceWorker:true,blockingMarkers:0},null,2));
