import fs from 'node:fs';import path from 'node:path';import vm from 'node:vm';import {spawnSync} from 'node:child_process';
const cwd=process.cwd(),read=p=>fs.readFileSync(path.join(cwd,p),'utf8'),exists=p=>fs.existsSync(path.join(cwd,p)),fail=m=>{throw new Error(m)};
const syntaxCheck=p=>{const r=spawnSync(process.execPath,['--check',p],{cwd,encoding:'utf8'});if(r.status!==0)fail(`${p} syntax failed: ${r.stderr||r.stdout}`)};
const pngDimensions=p=>{const b=fs.readFileSync(path.join(cwd,p));if(b.length<24||b.toString('hex',0,8)!=='89504e470d0a1a0a')fail(`invalid PNG ${p}`);return[b.readUInt32BE(16),b.readUInt32BE(20)]};
const manifest=JSON.parse(read('manifest.webmanifest'));for(const k of ['name','short_name','start_url','scope','display','background_color','theme_color','icons'])if(!manifest[k])fail(`manifest missing ${k}`);if(manifest.display!=='standalone')fail('manifest display must be standalone');const declaredIcons=new Map(manifest.icons.map(i=>[i.src,i]));for(const[src,size]of[['icons/icon-192.png',192],['icons/icon-512.png',512],['icons/icon-maskable-512.png',512]]){if(!declaredIcons.has(src)||!exists(src))fail(`missing icon ${src}`);const[w,h]=pngDimensions(src);if(w!==size||h!==size)fail(`icon dimensions ${src}: ${w}x${h}`)}
const version=JSON.parse(read('pwa-version.json'));if(version.schemaVersion!==1||version.buildId!=='p6-2026-08-25-r18'||!version.dataVersion)fail('pwa-version invalid');if('canonicalDataFiles'in version||'derivedRuntimeData'in version)fail('runtime version file still contains canonical verification contract');
const required=['index.html','p5.css','p5_app.js','practice_navigation.js','reader_sheet.js','p6_private_data.js','p6_pwa.css','p6_pwa.js','P2_learning.html','008_cue_practice_P3.html','009_rehearsal_P4.html','mousetrap_line_structure.json','manifest.webmanifest','pwa-version.json','offline.html','upgrade-r18.html','sw.js','scripts/assemble-production.mjs','scripts/build-learning-structure.mjs','tests/startup_smoke.mjs'];for(const f of required)if(!exists(f))fail(`missing required asset ${f}`);
for(const legacy of ['pages_private_import.js','bootstrap_watchdog.js','bootstrap_entry.js'])if(exists(legacy))fail(`obsolete runtime must be deleted: ${legacy}`);
for(const f of ['practice_navigation.js','reader_sheet.js','p6_private_data.js','p6_pwa.js','sw.js','tests/startup_smoke.mjs','scripts/build-learning-structure.mjs','scripts/assemble-production.mjs'])syntaxCheck(f);new vm.Script(read('p5_app.js'),{filename:'p5_app.js'});
const html=read('index.html');for(const t of ['src="p5_app.js?v=r18"','src="practice_navigation.js?v=r18"','src="reader_sheet.js?v=r18"','src="p6_pwa.js?v=r18"','id="dataStatus"','id="learningOverlay"','id="wordOverlay"','id="cueFrame"','id="rehearsalFrame"','台本を覚える'])if(!html.includes(t))fail(`index missing ${t}`);for(const forbidden of ['dataGate','gateStatus','retryBtn','pagesDataBtn','pagesDataFiles','Production Data','Private data','bootstrap_entry.js','bootstrap_watchdog.js'])if(html.includes(forbidden))fail(`legacy startup UI remains in index: ${forbidden}`);
const compat=read('p6_private_data.js');for(const t of ['STATIC_COMPAT_ONLY','getVerifiedResponse','getVerifiedJson',"fetch(`./${path}`"])if(!compat.includes(t))fail(`static compatibility adapter missing ${t}`);for(const forbidden of ['caches.open','crypto.subtle','sha256','canonicalDataFiles','mts:data-progress','queueCacheWrite','readOfflineCache'])if(compat.includes(forbidden))fail(`compatibility adapter regained obsolete resolver behavior: ${forbidden}`);
const upgrade=read('upgrade-r18.html');for(const t of ['getRegistrations','unregister','caches.keys','mts-pwa-','mts-build','r18'])if(!upgrade.includes(t))fail(`upgrade escape page missing ${t}`);
const structure=JSON.parse(read('mousetrap_line_structure.json'));if(structure.schemaVersion!==1||!structure.copyrightSafe)fail('structure schema/copyright contract invalid');if(structure.counts?.speeches!==1164||structure.counts?.sentences!==2277||structure.counts?.chunks!==8055)fail('structure declared counts invalid');if(structure.materializedCounts?.speeches!==1164||structure.materializedCounts?.sentences!==2277||structure.materializedCounts?.chunks!==8057)fail('structure materialized counts invalid');if(structure.mappingStats?.fullCoverage!==1161||structure.mappingStats?.fallback!==3)fail('structure mapping stats invalid');
const roles=new Set(['S','V','O','C','M',"S'","V'","O'","C'"]),types=new Set(['NP','VP','PP','AdvP','AdjP','NC','AC','AdvC','Inf','Gerund','Participle','PhrasalVerb','FixedExpression']);const mapped=Object.entries(structure.lines||{}),fallback=Object.entries(structure.rawLines||{});if(mapped.length!==1161||fallback.length!==3)fail('structure speech coverage invalid');let sc=0,cc=0;function validateChunks(s,n){let cur=0;if(!Array.isArray(s.chunks)||!s.chunks.length)fail(`empty chunks ${s.id}`);for(const c of s.chunks){if(c.start!==cur||c.end<=c.start)fail(`chunk coverage ${c.id}`);if(!roles.has(c.role)||!types.has(c.type))fail(`chunk label ${c.id}`);if('text'in c)fail(`structure duplicates source text ${c.id}`);cur=c.end;cc++}if(cur!==n)fail(`sentence reconstruction length ${s.id}`)}for(const[,line]of mapped)for(const s of line.sentences){validateChunks(s,s.expectedLength);sc++}for(const[,line]of fallback)for(const s of line.sentences){validateChunks(s,s.expectedLength);sc++}if(sc!==2277||cc!==8057)fail(`structure counts sentences=${sc} chunks=${cc}`);
const p5=read('p5_app.js');for(const t of ["fetch(`./${path}`)",'dataStatus','MTS_SHARED_LINE_ANNOTATIONS','MTS_SHARED_WORD_DICTIONARY','#/search',"m.target==='home'"])if(!p5.includes(t))fail(`p5 invariant missing ${t}`);for(const forbidden of ['dataGate','gateStatus','retryBtn','pagesDataBtn','pagesDataFiles','PRODUCTION DATA UNAVAILABLE','SHA-256'])if(p5.includes(forbidden))fail(`legacy startup dependency remains in p5_app.js: ${forbidden}`);
const sheet=read('reader_sheet.js');for(const t of ['openLine','closeLine','openWord','maskLine','MTS_STUDY_ANYWHERE','mousetrap_line_structure.json','memoryStages'])if(!sheet.includes(t))fail(`study layer missing ${t}`);if(!sheet.includes('background:none!important'))fail('underline-only vocabulary styling missing');
const p2=read('P2_learning.html');for(const t of ['Structure','S / V / O / C / M','詳しく見る','Grammar / Usage','mousetrap_line_structure.json','struct-chunk','p6_private_data.js'])if(!p2.includes(t))fail(`Line sheet UI missing ${t}`);
for(const f of ['008_cue_practice_P3.html','009_rehearsal_P4.html']){const src=read(f);if(!src.includes('p6_private_data.js')||!src.includes('MTS_PRIVATE_DATA'))fail(`${f} must use the thin static compatibility adapter until its legacy inline loader is removed`)}
const sw=read('sw.js');for(const t of [version.buildId,'RUNTIME_ASSETS','mousetrap_script_data.json','mousetrap_line_structure.json','upgrade-r18.html','networkFirst','skipWaiting','clients.claim'])if(!sw.includes(t))fail(`sw missing ${t}`);for(const forbidden of ['bootstrap_entry.js','canonicalDataFiles','sha256','crypto.subtle','DATA_HASH','pages_private_import.js','warmCanonicalData'])if(sw.includes(forbidden))fail(`obsolete service worker path remains: ${forbidden}`);const networkPos=sw.indexOf('await fetch(request'),cachePos=sw.indexOf('await cache.match');if(networkPos<0||cachePos<0||networkPos>cachePos)fail('service worker shell/runtime path is not network-first');
const nav=read('practice_navigation.js');for(const t of ['homeBtn','setupCancelBtn','pauseExitBtn'])if(!nav.includes(t))fail(`practice navigation missing ${t}`);
const builder=read('scripts/build-learning-structure.mjs');for(const t of ['2277','8055','8057','DECLARED_METADATA_MISMATCH','010_CHARACTER_INDEX.txt'])if(!builder.includes(t))fail(`structure builder missing ${t}`);
const productionRuntime=['index.html','p5_app.js','practice_navigation.js','reader_sheet.js','p6_private_data.js','p6_pwa.js','P2_learning.html','008_cue_practice_P3.html','009_rehearsal_P4.html','sw.js'];const unresolved=/\b(?:TODO|FIXME|coming soon|not implemented|placeholder|dummy|fake|temporary)\b/i;for(const f of productionRuntime){const src=read(f).replace(/\bplaceholder\s*=\s*(["']).*?\1/gi,'');if(unresolved.test(src))fail(`blocking marker in ${f}`)}
console.log(JSON.stringify({status:'PASS',buildId:version.buildId,startup:{homeInInitialHtml:true,directScriptBoot:true,directStaticJson:true,fullScreenDataGate:false,browserShaVerification:false,blockingMigrationBootstrap:false,networkFirstServiceWorker:true,escapePage:true,smokeTest:true},structure:{declaredSentences:2277,declaredChunks:8055,materializedChunks:8057,fullCoverage:1161,fallback:3},practiceNavigation:true},null,2));
