const {test,expect}=require('@playwright/test');
const BASE='http://127.0.0.1:4173/index.html';
async function ready(page){await page.goto(BASE,{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>window.MTS_INDEX_ZERO?.store?.hasCore?.(),null,{timeout:12000});await page.evaluate(()=>Promise.all([MTS_INDEX_ZERO.store.loadStudy(),MTS_INDEX_ZERO.store.loadStructure()]));await page.waitForFunction(()=>MTS_INDEX_ZERO.store.hasStudy()&&MTS_INDEX_ZERO.store.hasStructure(),null,{timeout:15000})}

async function nestedSample(page){return page.evaluate(()=>{for(const scene of ['act1-scene1','act1-scene2','act2'])for(const speech of MTS_INDEX_ZERO.store.getScene(scene)){const structure=MTS_INDEX_ZERO.store.getStructure(speech.id);if(structure?.sentences?.some(s=>s.clauses?.some(c=>c.parentClauseId)&&s.chunks?.some(c=>c.marker==='HV')))return{scene,line:speech.id}}return null})}

test('dictionary uses occurrence meaning and exposes no Pattern or generic play paraphrase',async({page})=>{await ready(page);const audit=await page.evaluate(()=>{let pattern=0,generic=0;for(const entry of Object.values(MTS_INDEX_ZERO.store.dictionary||{})){if('pattern'in entry||'patternDesc'in entry)pattern++;const c=String(entry.contextExplanation||'');if(/^(劇中では|この劇では)/.test(c)||/前後関係からこの意味を取る。?$/.test(c))generic++}return{pattern,generic}});expect(audit).toEqual({pattern:0,generic:0});const sample=await page.evaluate(()=>{for(const scene of ['act1-scene1','act1-scene2','act2'])for(const speech of MTS_INDEX_ZERO.store.getScene(scene)){const v=MTS_INDEX_ZERO.store.getVocabulary(speech.id)[0];if(v)return{scene,line:speech.id,meaning:v.meaning}}return null});expect(sample).toBeTruthy();await page.goto(BASE+'#/line?scene='+sample.scene+'&line='+sample.line);await page.locator('.word-row').first().click();await expect(page.locator('#word-overlay')).toBeVisible();const labels=await page.locator('.word-dict-card dt').allTextContents();expect(labels).not.toContain('Pattern');expect(labels).not.toContain('In this play');await expect(page.locator('.word-dict-card dd').first()).toHaveText(sample.meaning)});

test('Structure is rebuilt from canonical markers with muted span presentation',async({page},testInfo)=>{await ready(page);const sample=await nestedSample(page);expect(sample).toBeTruthy();await page.goto(BASE+'#/line?scene='+sample.scene+'&line='+sample.line);await page.locator('.structure-summary').click();await expect(page.locator('.syntax-view')).toBeVisible();await expect(page.locator('[data-clause-marker]').first()).toBeVisible();await expect(page.locator('[data-syntax-depth="1"]').first()).toBeVisible();await expect(page.locator('[data-marker="HV"]').first()).toBeVisible();await expect(page.locator('[data-marker^="S"]').first()).toBeVisible();await expect(page.locator('.structure-sentence,.structure-clause,.structure-chunk')).toHaveCount(0);const visual=await page.locator('[data-syntax-chunk-id]').first().evaluate(el=>{const text=el.querySelector('.syntax-chunk-text');const s=getComputedStyle(el),t=getComputedStyle(text);return{background:s.backgroundColor,border:s.borderBottomWidth,text:t.color}});expect(visual.background).toBe('rgba(0, 0, 0, 0)');expect(visual.border).toBe('2px');expect(visual.text).toBe('rgb(39, 35, 31)');const first=page.locator('[data-syntax-chunk-id]').first();const marker=await first.getAttribute('data-marker');await first.click();await expect(page.locator('.syntax-detail:not([hidden])').first()).toContainText(marker);await testInfo.attach('structure-approved-visual',{body:await page.screenshot({fullPage:true}),contentType:'image/png'})});

test('fragment analysis remains fragment-first instead of fabricated S/V',async({page})=>{await ready(page);const sample=await page.evaluate(()=>{for(const scene of ['act1-scene1','act1-scene2','act2'])for(const speech of MTS_INDEX_ZERO.store.getScene(scene)){const structure=MTS_INDEX_ZERO.store.getStructure(speech.id);if(structure?.sentences?.some(s=>s.kind==='fragment'&&s.chunks?.length))return{scene,line:speech.id}}return null});expect(sample).toBeTruthy();await page.goto(BASE+'#/line?scene='+sample.scene+'&line='+sample.line);await page.locator('.structure-summary').click();await expect(page.locator('.syntax-fragment').first()).toBeVisible();await expect(page.getByText('undefined',{exact:true})).toHaveCount(0)});

test('expanded Structure wraps on a 360px viewport without horizontal overflow',async({page})=>{await page.setViewportSize({width:360,height:800});await ready(page);const sample=await nestedSample(page);await page.goto(BASE+'#/line?scene='+sample.scene+'&line='+sample.line);await page.locator('.structure-summary').click();const overflow=await page.locator('.syntax-view').evaluate(el=>el.scrollWidth-el.clientWidth);expect(overflow).toBeLessThanOrEqual(1)});
